import { expect, test } from "@playwright/test"
import { completeQuickPlan, refinePlan } from "./plan-flow"
import { writeFile } from "node:fs/promises"

test.use({ serviceWorkers: "block" })
test.beforeEach(async ({ page }) => {
  await page.route("**/*", route => ["127.0.0.1", "localhost"].includes(new URL(route.request().url()).hostname) ? route.continue() : route.abort())
  await page.clock.setFixedTime(new Date(2026, 8, 27, 12))
})

test("compact overview keeps exact methods and opens the selected slot's progress without writing", async ({ page }, info) => {
  await page.setViewportSize({ width: 375, height: 667 })
  await page.goto("/?app=1&uitest=1")
  await page.getByRole("button", { name: "훈련 계획 만들기", exact: true }).click()
  await completeQuickPlan(page, { days: /^매일/u })
  await refinePlan(page, "하루 두 번", /하루 두 번 운동할게요/u)
  await page.getByRole("button", { name: "이 일정으로 시작" }).click()
  const before = await page.evaluate(() => localStorage.getItem("trainoracle.plan-beta.v1"))
  const overview = page.locator(".instant-plan--today-compact")
  await expect(overview).not.toContainText("아직 기록 없음")
  await expect(page.getByRole("button", { name: "날짜별 카드 보기" })).toBeVisible()
  await expect(page.getByRole("list", { name: "날짜별 계획 미리보기" })).toHaveCount(0)
  const picker = overview.getByRole("group", { name: "오늘 세션 선택" })
  await picker.getByRole("button", { name: /오후/ }).click()
  await expect(overview.locator(".instant-plan__session")).toContainText(/RPE/)
  const sessionSteps = overview.locator(".instant-plan__session .instant-plan__steps")
  await expect(sessionSteps).toContainText("본운동")
  await expect(sessionSteps).toContainText("전체 예정시간")
  const methodButton = overview.getByRole("button", { name: "오후 훈련 방법·근거" })
  await expect(methodButton).toBeVisible()
  await page.locator(".app-scroll-region").evaluate(el => { el.scrollTop = 0 })
  await page.screenshot({ path: info.outputPath("compact-plan-375.png") })
  const overviewMetrics = await page.evaluate(() => ({
    gridTop: document.querySelector(".plan-training-flow .month-calendar__grid")?.getBoundingClientRect().top,
    overviewBottom: document.querySelector(".instant-plan--today-compact")?.getBoundingClientRect().bottom,
    viewport: { width: innerWidth, height: innerHeight },
    overflow: document.documentElement.scrollWidth > innerWidth,
  }))
  expect(overviewMetrics.overflow).toBe(false)
  await writeFile(info.outputPath("compact-layout-metrics.json"), JSON.stringify(overviewMetrics, null, 2))
  await page.setViewportSize({ width: 320, height: 568 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: info.outputPath("compact-plan-320.png") })
  await page.setViewportSize({ width: 375, height: 667 })
  await methodButton.click()
  const methodReader = page.getByRole("dialog", { name: "2026년 9월 27일 일요일" })
  await expect(methodReader.getByRole("button", { name: "오후", exact: true })).toHaveAttribute("aria-current", "location")
  await expect(methodReader.locator('[data-session-slot="PM"] [data-session-records]')).not.toHaveAttribute("open")
  await methodReader.getByRole("button", { name: "달력으로 돌아가기" }).click()
  await expect(methodButton).toBeFocused()
  await overview.getByRole("button", { name: "휴식·건너뜀 기록" }).click()
  const reader = page.getByRole("dialog", { name: "2026년 9월 27일 일요일" })
  const afternoon = reader.getByRole("group", { name: "9월 27일 일요일 오후 세션" })
  await expect(afternoon.getByRole("button", { name: "휴식", exact: true })).toBeVisible()
  await expect(reader.getByRole("button", { name: "오후", exact: true })).toHaveAttribute("aria-current", "location")
  expect(await page.evaluate(() => localStorage.getItem("trainoracle.plan-beta.v1"))).toBe(before)
  await reader.screenshot({ path: info.outputPath("compact-progress-375.png") })
  await page.goBack()
  await expect(reader).not.toBeVisible()
  await expect(overview.getByRole("button", { name: "휴식·건너뜀 기록" })).toBeFocused()
  await overview.getByRole("button", { name: "휴식·건너뜀 기록" }).click()
  await expect(afternoon.getByRole("button", { name: "휴식", exact: true })).toBeVisible()
  expect(await page.evaluate(() => localStorage.getItem("trainoracle.plan-beta.v1"))).toBe(before)
})

test("cycle browsing clearly separates month totals and can return to the selected range", async ({ page }, info) => {
  await page.goto("/?app=1&uitest=1")
  await page.getByRole("navigation", { name: "주 탭" }).getByRole("button", { name: "일지", exact: true }).click()
  await page.getByRole("button", { name: "9.5일 주기", exact: true }).click()
  await expect(page.getByRole("button", { name: "월간 달력으로", exact: true })).toBeVisible()
  await page.getByRole("button", { name: "다음 달", exact: true }).click()
  await page.getByRole("button", { name: "다음 달", exact: true }).click()
  await expect(page.getByRole("grid", { name: "2026년 11월 달력" })).toBeVisible()
  await expect(page.getByText("이 달 0일 · 0개 기록", { exact: true })).toBeVisible()
  await page.screenshot({ path: info.outputPath("cycle-outside-range.png") })
  await page.getByRole("button", { name: "선택한 주기로 이동", exact: true }).click()
  await expect(page.getByRole("grid", { name: "2026년 9월 달력" })).toBeVisible()
  await page.getByRole("button", { name: "월간 달력으로", exact: true }).click()
  await expect(page.getByRole("button", { name: "월간 달력", exact: true })).toHaveAttribute("aria-pressed", "true")
})

test("an empty past date writes that date and returns to its month; future dates cannot log performance", async ({ page }, info) => {
  await page.goto("/?app=1&uitest=1")
  await page.getByRole("navigation", { name: "주 탭" }).getByRole("button", { name: "일지", exact: true }).click()
  await page.getByRole("button", { name: "내 달력", exact: true }).click()
  await page.getByRole("button", { name: /년월과 날짜 이동/ }).click()
  await page.getByLabel("날짜로 이동", { exact: true }).fill("2026-08-15")
  const reader = page.getByRole("dialog", { name: "2026년 8월 15일 토요일" })
  await reader.getByRole("button", { name: "이날 일지 쓰기" }).click()
  await expect(reader).not.toBeVisible()
  await expect(page.getByText(/2026.08.15|2026-08-15|8월 15일/).first()).toBeVisible()
  await page.screenshot({ path: info.outputPath("past-date-writing.png") })
  await page.goBack()
  await page.getByRole("button", { name: "내 달력", exact: true }).click()
  await expect(page.getByRole("grid", { name: "2026년 8월 달력" })).toBeVisible()
  await page.getByRole("button", { name: /년월과 날짜 이동/ }).click()
  await page.getByLabel("날짜로 이동", { exact: true }).fill("2028-02-29")
  await expect(page.getByRole("dialog", { name: "2028년 2월 29일 화요일" })).toBeVisible()
  await expect(page.getByRole("button", { name: "이날 일지 쓰기" })).toHaveCount(0)
})
