import { expect, test } from "@playwright/test"
import { completeQuickPlan, openPlanOptions, refinePlan } from "./plan-flow"

for (const [width, zoom] of [[320, 1], [375, 2], [1280, 1]] as const) {
  test(`schedule condition review ${width}px zoom ${zoom}`, async ({ page, context }, info) => {
    const errors: string[] = [], blocked: string[] = []
    page.on("pageerror", error => errors.push(error.message))
    await context.route("**/*", route => {
      const request = route.request(), url = new URL(request.url())
      if (url.origin !== "http://127.0.0.1:4428" || !["GET", "HEAD"].includes(request.method())) {
        blocked.push(`${request.method()} ${url.origin}`)
        return route.abort()
      }
      return route.continue()
    })
    await page.setViewportSize({ width, height: 800 })
    await page.emulateMedia({ reducedMotion: zoom === 2 ? "reduce" : "no-preference" })
    await page.clock.setFixedTime(new Date("2026-10-02T03:00:00Z"))
    await page.goto("/?app=1&uitest=1")
    await page.getByRole("navigation", { name: "주 탭" }).getByRole("button", { name: "훈련", exact: true }).click()
    await completeQuickPlan(page, { event: "5000", experience: /빠른 훈련과 쉬운 훈련을 나눠 꾸준히 해왔어요/u, days: /^5일/u })
    await refinePlan(page, "훈련 종류", /스피드 훈련/u)
    await page.getByRole("button", { name: /공간 확인하고 상세 훈련 보기/u }).click()
    const picker = page.locator(".catalog-workout-picker")
    const address = await picker.getByRole("combobox", { name: "바꿀 일정" }).inputValue()
    const id = await picker.getByRole("combobox", { name: "훈련 구성" }).inputValue()
    await picker.getByRole("checkbox", { name: "가속하고 속도를 줄일 충분한 공간이 있어요" }).check()
    await picker.getByRole("button", { name: "이 구성으로 바꾸기" }).click()
    const start = page.getByRole("button", { name: "이 일정으로 시작", exact: true })
    await expect(start).toBeEnabled()
    await openPlanOptions(page)
    await page.getByLabel("계획 시작 날짜", { exact: true }).fill("2026-11-02")
    await page.getByRole("button", { name: "바뀐 날짜의 운동 환경 확인" }).click()
    const review = page.getByRole("group", { name: "이 날짜에도 운동할 환경이 갖춰져 있나요?" })
    await expect(review).toBeVisible()
    await expect(review.getByRole("checkbox")).not.toBeChecked()
    await expect(start).toBeDisabled()
    await expect(review).toContainText("2026-11-")
    if (zoom !== 1) await page.addStyleTag({ content: `html { zoom: ${zoom}; }` })
    await review.scrollIntoViewIfNeeded()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth + 1)).toBe(true)
    const hit = await review.getByRole("checkbox").locator("..").boundingBox()
    expect(hit!.height).toBeGreaterThanOrEqual(44)
    await page.screenshot({ path: info.outputPath("schedule-review.png") })
    expect(await page.evaluate(() => localStorage.getItem("trainoracle.plan-beta.v1"))).toBeNull()
    await review.getByRole("checkbox").check()
    await expect(start).toBeDisabled()
    await review.getByRole("button", { name: "이 날짜의 조건 확인" }).click()
    await expect(review).toHaveCount(0)
    await expect(start).toBeEnabled()
    expect(await page.evaluate(() => localStorage.getItem("trainoracle.plan-beta.v1"))).toBeNull()
    await start.click()
    await expect(page.getByRole("heading", { name: "첫 훈련을 확인하세요", exact: true })).toBeVisible()
    const raw = await page.evaluate(() => localStorage.getItem("trainoracle.plan-beta.v1"))
    const state = JSON.parse(raw!), [day, slot] = address.split(":")
    expect(state.intake.startDate).toBe("2026-11-02")
    const selected = state.activePlan.sessions.find((s: { day: number; slot: string }) => s.day === Number(day) && s.slot === slot)
    expect(selected.prescription.catalogWorkout.catalogId).toBe(id)
    await page.reload()
    expect(await page.evaluate(() => localStorage.getItem("trainoracle.plan-beta.v1"))).toBe(raw)
    expect(errors).toEqual([])
    expect(blocked).toEqual([])
  })
}
