import { expect, test } from "@playwright/test"
import { completeQuickPlan, refinePlan } from "./plan-flow"

for (const [width, zoom, reduced] of [[320, 1, false], [375, 2, true], [1280, 1, true]] as const) {
  test(`condition review ${width}px zoom ${zoom}`, async ({ page, context }, info) => {
    const errors: string[] = [], blocked: string[] = []
    page.on("pageerror", error => errors.push(error.message))
    await context.route("**/*", route => {
      const request = route.request(), url = new URL(request.url())
      if (url.origin !== "http://127.0.0.1:4427" || !["GET", "HEAD"].includes(request.method())) {
        blocked.push(`${request.method()} ${url.origin}`)
        return route.abort()
      }
      return route.continue()
    })
    await page.setViewportSize({ width, height: 800 })
    await page.emulateMedia({ reducedMotion: reduced ? "reduce" : "no-preference" })
    await page.clock.setFixedTime(new Date("2026-10-02T03:00:00Z"))
    await page.goto("/?app=1&uitest=1")
    await page.getByRole("navigation", { name: "주 탭" }).getByRole("button", { name: "훈련", exact: true }).click()
    await completeQuickPlan(page, { event: "5000", experience: /빠른 훈련과 쉬운 훈련을 나눠 꾸준히 해왔어요/u, days: /^5일/u })
    await refinePlan(page, "훈련 종류", /스피드.*ATP-PC/u)
    if (zoom !== 1) await page.addStyleTag({ content: `html { zoom: ${zoom}; }` })
    const shortcut = page.getByRole("button", { name: /공간 확인하고 상세 훈련 보기/u })
    await expect(shortcut).toBeEnabled()
    await shortcut.scrollIntoViewIfNeeded()
    await page.screenshot({ path: info.outputPath("condition-offer.png") })
    await shortcut.click()
    const picker = page.locator(".catalog-workout-picker")
    await expect(picker).toHaveAttribute("open", "")
    const address = await picker.getByRole("combobox", { name: "바꿀 일정" }).inputValue()
    const id = await picker.getByRole("combobox", { name: "훈련 구성" }).inputValue()
    const check = picker.getByRole("checkbox", { name: "가속하고 속도를 줄일 충분한 공간이 있어요" })
    await expect(check).not.toBeChecked()
    await expect(picker.getByRole("spinbutton")).toHaveCount(0)
    await expect(picker.getByRole("button", { name: "이 구성으로 바꾸기" })).toBeDisabled()
    await check.check()
    await expect(page.getByRole("button", { name: "이 일정으로 시작", exact: true })).toBeDisabled()
    expect(await page.evaluate(() => localStorage.getItem("trainoracle.plan-beta.v1"))).toBeNull()
    await picker.getByRole("button", { name: "이 구성으로 바꾸기" }).click()
    await expect(shortcut).toHaveCount(0)
    expect(await page.evaluate(() => localStorage.getItem("trainoracle.plan-beta.v1"))).toBeNull()
    await page.getByRole("button", { name: "이 일정으로 시작", exact: true }).click()
    await expect(page.getByRole("heading", { name: "오늘 훈련", exact: true })).toBeVisible()
    const raw = await page.evaluate(() => localStorage.getItem("trainoracle.plan-beta.v1"))
    expect(raw).not.toBeNull()
    const state = JSON.parse(raw!), [day, slot] = address.split(":")
    const selected = state.activePlan.sessions.find((s: { day: number; slot: string }) => s.day === Number(day) && s.slot === slot)
    expect(selected.prescription.catalogWorkout.catalogId).toBe(id)
    expect(selected.prescription.catalogWorkout.inputs.confirmedRequirements).toEqual(["ACCELERATION_AND_DECELERATION_SPACE"])
    expect(selected.prescription.catalogWorkout.acceptedDurationSeconds).toBeUndefined()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth + 1)).toBe(true)
    await page.screenshot({ path: info.outputPath("active-plan.png") })
    await page.reload()
    await page.getByRole("navigation", { name: "주 탭" }).getByRole("button", { name: "훈련", exact: true }).click()
    await expect(page.getByRole("heading", { name: "오늘 훈련", exact: true })).toBeVisible()
    expect(await page.evaluate(() => localStorage.getItem("trainoracle.plan-beta.v1"))).toBe(raw)
    expect(errors).toEqual([])
    expect(blocked).toEqual([])
  })
}
