import { expect, test } from "@playwright/test"
import { completeQuickPlan } from "./plan-flow"

for (const width of [320, 375]) {
  test.describe(`feature discovery ${width}px`, () => {
    test.use({ viewport: { width, height: 740 }, reducedMotion: "reduce" })
    test("keeps named tools reachable and returns to the actual origin", async ({ page }, info) => {
      const errors: string[] = []
      page.on("pageerror", error => errors.push(error.message))
      await page.route("**/*", route => new URL(route.request().url()).hostname === "127.0.0.1" ? route.continue() : route.abort())
      await page.goto("/?app=1&uitest=1")
      await page.getByRole("button", { name: "더보기", exact: true }).click()
      await expect(page.getByRole("button", { name: "페이스 계산", exact: true })).toBeVisible()
      await page.screenshot({ path: info.outputPath("more-tools.png"), fullPage: true })
      for (const name of ["페이스 계산", "경기 기록 추가·수정", "워치 파일 가져오기", "나의 러닝 프로필", "최고기록으로 풀이하기", "오라클 읽을거리", "훈련법 읽기", "일지 꾸미기·포인트"]) {
        const entry = page.getByRole("button", { name, exact: true })
        await expect(entry).toBeVisible()
        expect(await entry.evaluate(node => node.closest("details") === null)).toBe(true)
      }
      await page.getByRole("button", { name: "경기 기록 추가·수정", exact: true }).click()
      await expect(page.getByRole("button", { name: "더보기로", exact: true })).toBeVisible()
      await page.goBack()
      await expect(page.getByRole("heading", { name: "더보기", exact: true })).toBeVisible()
      await page.getByRole("button", { name: "워치 파일 가져오기", exact: true }).click()
      await expect(page.getByRole("heading", { name: "워치 기록 불러오기", exact: true })).toBeVisible()
      await page.getByRole("button", { name: "뒤로", exact: true }).click()
      await page.getByRole("button", { name: "오라클 읽을거리", exact: true }).click()
      await expect(page.locator(".oracle-v2__chrome").getByText("오라클 읽을거리", { exact: true })).toBeVisible()
      await expect(page.getByRole("group", { name: "읽을거리 주제" })).toBeVisible()
      await page.getByRole("button", { name: "더보기로 돌아가기", exact: true }).click()
      await page.getByRole("button", { name: "나의 러닝 프로필", exact: true }).click()
      await expect(page.getByRole("button", { name: "친구와 취향 비교", exact: true })).toBeVisible()
      await page.getByRole("button", { name: "친구와 취향 비교", exact: true }).click()
      await expect(page.getByRole("heading", { name: "어떻게 비교할까요?", exact: true })).toBeVisible()
      await expect(page.getByRole("button", { name: "직접 입력해서 비교", exact: true })).toBeEnabled()
      await page.getByRole("button", { name: "닫기", exact: true }).click()
      for (const name of ["내 훈련 해설", "내 기록 해설", "계획·수행 비교"]) {
        const entry = page.getByRole("button", { name, exact: true })
        await expect(entry).toBeVisible()
        expect(await entry.evaluate(node => node.closest("details") === null)).toBe(true)
      }
      await page.screenshot({ path: info.outputPath("profile-actions.png"), fullPage: true })
      await page.getByRole("button", { name: "더보기로 돌아가기", exact: true }).click()
      await page.getByRole("button", { name: "홈으로 돌아가기", exact: true }).click()
      await page.getByRole("navigation", { name: "주 탭" }).getByRole("button", { name: "오라클", exact: true }).click()
      await expect(page.getByRole("button", { name: "첫 기록 남기기", exact: true })).toBeInViewport()
      await expect(page.getByText("오라클 예시 보기", { exact: true })).toBeVisible()
      await page.screenshot({ path: info.outputPath("oracle-first.png") })
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
      await page.evaluate(() => {
        const sizes = Array.from(document.querySelectorAll<HTMLElement>("body *"))
          .filter(element => element instanceof HTMLElement && element.getClientRects().length > 0)
          .map(element => ({ element, size: parseFloat(getComputedStyle(element).fontSize) }))
        for (const { element, size } of sizes) element.style.setProperty("font-size", `${size * 2}px`, "important")
      })
      await page.screenshot({ path: info.outputPath("oracle-double-text.png") })
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
      expect(errors).toEqual([])
    })
  })
}

test("plan session exposes writing directly and does not confuse journal save with plan completion", async ({ page }, info) => {
  await page.setViewportSize({ width: 375, height: 740 })
  await page.clock.setFixedTime(new Date("2026-10-06T03:00:00Z"))
  await page.route("**/*", route => new URL(route.request().url()).hostname === "127.0.0.1" ? route.continue() : route.abort())
  await page.goto("/?app=1&uitest=1")
  await page.getByRole("navigation", { name: "주 탭" }).getByRole("button", { name: "훈련", exact: true }).click()
  await completeQuickPlan(page, { event: "800m" })
  await page.getByRole("button", { name: "이 일정으로 시작", exact: true }).click()
  await expect(page.getByRole("heading", { name: "9일 훈련 계획", exact: true })).toBeVisible()
  const before = await page.evaluate(() => JSON.parse(localStorage.getItem("trainoracle.plan-beta.v1") ?? "null"))
  const session = before.activePlan.sessions.find((item: { role: string }) => item.role !== "REST")
  const date = new Date(before.intake.startDate + "T00:00:00Z")
  date.setUTCDate(date.getUTCDate() + session.day - 1)
  await page.locator(`button[data-date="${date.toISOString().slice(0, 10)}"]`).click()
  const selected = page.getByRole("dialog").locator(`[data-session-slot="${session.slot}"]`)
  const write = selected.getByRole("button", { name: "이 훈련 일지 쓰기", exact: true })
  await expect(write).toBeVisible()
  expect(await write.evaluate(node => node.closest("details") === null)).toBe(true)
  await page.screenshot({ path: info.outputPath("plan-direct-journal.png") })
  await write.click()
  await page.getByRole("button", { name: "계획대로 마쳤어요", exact: true }).click()
  await page.getByRole("button", { name: session.slot === "PM" ? "오후" : "오전", exact: true }).click()
  await page.getByRole("button", { name: /^RPE 6,/ }).click()
  await page.getByRole("button", { name: "없어요", exact: true }).click()
  await page.getByRole("button", { name: "이대로 저장", exact: true }).click()
  await expect(page.getByRole("heading", { name: "오늘 기록을 남겼어요.", exact: true })).toBeVisible()
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem("trainoracle.plan-beta.v1") ?? "null").progress)).toEqual(before.progress)
  await page.getByRole("button", { name: "완료", exact: true }).click()
  await expect(page.getByRole("dialog").locator(`[data-session-slot="${session.slot}"]`)).toBeVisible()
  await expect(page.getByRole("dialog").getByText("수행 기록 있음", { exact: true })).toBeVisible()
  await page.getByRole("button", { name: "달력으로 돌아가기", exact: true }).click()
  await expect(page.getByRole("dialog")).toHaveCount(0)
  await expect(page.locator(`button[data-date="${date.toISOString().slice(0, 10)}"]`)).toBeFocused()
})
