import { expect, test } from "@playwright/test"
import { completeQuickPlan, refinePlan } from "./plan-flow"

test.use({ serviceWorkers: "block" })

test("enlarged AM/PM reader, nested records, back restoration and linked writing", async ({ page }, info) => {
  await page.route("**/*", route => {
    const host = new URL(route.request().url()).hostname
    return host === "127.0.0.1" || host === "localhost" ? route.continue() : route.abort()
  })
  await page.clock.setFixedTime(new Date(2026, 8, 27, 12))
  await page.goto("/?app=1&uitest=1")
  await page.getByRole("button", { name: "훈련 계획 만들기", exact: true }).click()
  await completeQuickPlan(page, { days: /^매일/u })
  await refinePlan(page, "하루 두 번", /하루 두 번 운동할게요/u)
  await page.getByRole("button", { name: "이 일정으로 시작" }).click()
  const planBefore = await page.evaluate(() => localStorage.getItem("trainoracle.plan-beta.v1"))
  const calendar = page.getByRole("grid", { name: "2026년 9월 달력" })
  const date = calendar.getByRole("button", { name: /2026년 9월 27일 일요일/u })
  await date.click()
  const reader = page.getByRole("dialog", { name: "2026년 9월 27일 일요일" })
  await expect(reader).toBeVisible()
  for (const width of [320, 375, 1024]) {
    await page.setViewportSize({ width, height: 800 })
    expect(await reader.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
    const bounds = await reader.boundingBox()
    expect(bounds!.width).toBe(width)
    expect(bounds!.height).toBeCloseTo(800, 1)
    await reader.screenshot({ path: info.outputPath(`day-reader-${width}.png`) })
  }
  await page.setViewportSize({ width: 375, height: 667 })
  await reader.getByRole("navigation", { name: "오전·오후 바로가기" }).getByRole("button", { name: "오후", exact: true }).click()
  const afternoon = reader.getByRole("group", { name: "9월 27일 일요일 오후 세션" })
  await expect(afternoon).toBeFocused()
  await expect(reader.getByRole("button", { name: "오후", exact: true })).toHaveAttribute("aria-current", "location")
  await afternoon.getByText("일지·진행 기록", { exact: true }).click()
  await afternoon.getByRole("button", { name: "연결된 일지 기록 보기" }).click()
  const recordReader = page.locator("dialog.session-explanation")
  await expect(recordReader.getByRole("tab", { name: "주기·기록" })).toHaveAttribute("aria-selected", "true")
  await expect(recordReader.getByRole("heading", { name: "실제 기록", exact: true })).toBeVisible()
  await page.goBack()
  await expect(recordReader).not.toBeVisible()
  await expect(reader).toBeVisible()
  await page.goBack()
  await expect(reader).not.toBeVisible()
  await expect(date).toBeFocused()
  await expect(calendar).toBeVisible()
  expect(await page.evaluate(() => localStorage.getItem("trainoracle.plan-beta.v1"))).toBe(planBefore)

  await date.click()
  await reader.evaluate(element => {
    const nodes = [element, ...element.querySelectorAll<HTMLElement>("*")].filter(node => !(node instanceof SVGElement))
    const sizes = nodes.map(node => parseFloat(getComputedStyle(node).fontSize))
    nodes.forEach((node, i) => (node as HTMLElement).style.setProperty("font-size", `${sizes[i]! * 2}px`, "important"))
  })
  expect(await reader.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
  await reader.screenshot({ path: info.outputPath("day-reader-200-percent.png") })
  await reader.getByRole("navigation", { name: "오전·오후 바로가기" }).getByRole("button", { name: "오후", exact: true }).click()
  await afternoon.getByText("일지·진행 기록", { exact: true }).click()
  await afternoon.getByRole("button", { name: "이 훈련 일지 쓰기" }).click()
  await expect(reader).not.toBeVisible()
  await expect(page.getByText(/계획.*오후|오후.*계획/u).first()).toBeVisible()
  expect(await page.evaluate(() => localStorage.getItem("trainoracle.plan-beta.v1"))).toBe(planBefore)
})
