import { expect, test } from "@playwright/test"
import { completeDetailedPlan, openPlanOptions, openPlanRefinement } from "./plan-flow"
import { undersizedInteractiveTargets } from "./touch-audit"

test.use({ serviceWorkers: "block" })

test("switches method in place and saves only the reconfirmed prescription", async ({ page }, testInfo) => {
  if (testInfo.project.name === "mobile-chromium") await page.setViewportSize({ width: 375, height: 667 })
  await page.clock.setFixedTime(new Date("2026-09-02T03:00:00.000Z"))
  const errors: string[] = []
  page.on("pageerror", error => errors.push(error.message))
  await page.addInitScript(() => {
    if (localStorage.getItem("trainoracle.athlete-records.v1") !== null) return
    localStorage.setItem("trainoracle.athlete-records.v1", JSON.stringify([{
      schemaVersion: 1, id: "00000000-0000-4000-8000-000000005001", purpose: "RECENT_RESULT",
      eventDistanceM: 5000, performanceSeconds: 1111.25, achievedOn: "2026-08-15", seasonId: null,
      enteredBy: "ATHLETE", verificationState: "SELF_REPORTED", sourceRef: "athlete-record:00000000-0000-4000-8000-000000005001",
      savedAt: "2026-08-15T12:00:00.000Z",
    }]))
  })
  await page.goto("/?app=1")
  await page.getByRole("navigation", { name: "주 탭" }).getByRole("button", { name: "계획" }).click()
  await completeDetailedPlan(page, { event: /^5000m/u, division: /고등부/u,
    experience: /구조화된 훈련과 경기 경험이 많아요/u, focus: /숨차게 반복.*VO₂/u,
    time: /저녁에 운동해요/u, twice: true })
  await openPlanRefinement(page, "안내 방식")
  const support = page.locator(".plan-support-coverage")
  const supportToggle = support.locator("summary")
  await expect(support).not.toHaveAttribute("open")
  await supportToggle.focus()
  await supportToggle.press("Enter")
  await expect(support).toHaveAttribute("open")
  await expect(support.getByRole("row")).toHaveCount(8)
  for (const event of ["10km", "하프마라톤", "마라톤"]) {
    const row = support.getByRole("row").filter({ has: page.getByRole("rowheader", { name: event, exact: true }) })
    await expect(row.getByText("훈련 구성 109개 · 목적·시간·환경 확인 후 적용", { exact: true })).toBeVisible()
    await expect(row.getByText(`기록 기반 페이스 계산 구성 45개 · 기준 종목: 5km · ${event}`, { exact: true })).toBeVisible()
  }
  await expect(support.getByText(/지금 모두 적용할 수 있다는 뜻은 아니에요/u)).toBeVisible()
  await expect(support.getByText(/목표는 현재 능력이 아니에요/u)).toBeVisible()
  await expect(support.getByText("5 × 1km @ 5K RP · r150s Jog", { exact: true })).toBeVisible()
  expect((await supportToggle.boundingBox())!.height).toBeGreaterThanOrEqual(44)
  await supportToggle.scrollIntoViewIfNeeded()
  await page.screenshot({ path: testInfo.outputPath("support-coverage.png") })
  const middleSupportRow = support.getByRole("row", { name: /3000m/u })
  await middleSupportRow.scrollIntoViewIfNeeded()
  await expect(middleSupportRow).toBeInViewport({ ratio: 1 })
  await page.screenshot({ path: testInfo.outputPath("support-table-row.png") })
  const supportFont = await support.getByRole("table").evaluate(node => parseFloat(getComputedStyle(node).fontSize))
  await page.evaluate(size => document.documentElement.style.setProperty("--fs-body", `${size * 2}px`), supportFont)
  expect(await support.getByRole("table").evaluate(node => parseFloat(getComputedStyle(node).fontSize))).toBeGreaterThanOrEqual(supportFont * 1.9)
  await expect.poll(() => support.evaluate(node => node.scrollWidth <= node.clientWidth + 1)).toBe(true)
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await supportToggle.scrollIntoViewIfNeeded()
  await page.screenshot({ path: testInfo.outputPath("support-coverage-200pct.png") })
  // At 200%, the current catalog metadata may make one row taller than the
  // viewport. Verify every text part is readable by vertical scrolling, without
  // omitting text or shrinking it to force the whole row onto one screen.
  const rowParts = middleSupportRow.locator("th, p, strong, span")
  await expect(rowParts).toHaveCount(6)
  const withoutWhitespace = (value: string) => value.replace(/\s/gu, "")
  expect(withoutWhitespace((await rowParts.allTextContents()).join("")))
    .toBe(withoutWhitespace((await middleSupportRow.textContent()) ?? ""))
  for (const part of await rowParts.all()) {
    if (await part.evaluate(node => node.tagName === "TH")) {
      // A table header's box stretches to the entire row. Measure its actual
      // rendered text, not the empty cell area below it.
      await expect(part).toBeVisible()
      await expect(part).toHaveText("3000m")
      await part.evaluate(node => node.scrollIntoView({ block: "start" }))
      await expect.poll(() => part.evaluate(node => {
        if (!node.textContent?.trim()) return 0
        const range = document.createRange()
        range.selectNodeContents(node)
        const rects = [...range.getClientRects()].filter(rect => rect.width > 0 && rect.height > 0)
        if (rects.length === 0) return 0
        return Math.min(...rects.map(rect =>
          Math.max(0, Math.min(rect.right, innerWidth) - Math.max(rect.left, 0)) / rect.width
          * Math.max(0, Math.min(rect.bottom, innerHeight) - Math.max(rect.top, 0)) / rect.height))
      })).toBe(1)
    } else {
      await part.evaluate(node => node.scrollIntoView({ block: "center", inline: "nearest" }))
      await expect(part).toBeInViewport({ ratio: 1 })
    }
  }
  await page.screenshot({ path: testInfo.outputPath("support-table-row-200pct.png") })
  await page.evaluate(() => document.documentElement.style.removeProperty("--fs-body"))
  await supportToggle.press("Space")
  await expect(support).not.toHaveAttribute("open")
  await page.getByRole("button", { name: /RPE 기준으로 받기/u }).click()
  await openPlanOptions(page, true)
  const method = page.locator(".plan-method-picker")
  const summary = method.locator(":scope > summary")
  const openMethodChoices = async () => {
    const choices = method.getByText("훈련 목록·다른 설정", { exact: true }).locator("..")
    if (await choices.getAttribute("open") === null) await choices.locator(":scope > summary").click()
  }
  await expect(method).not.toHaveAttribute("open")
  await summary.focus()
  await summary.press("Enter")
  await expect(method).toHaveAttribute("open")
  await openMethodChoices()
  await expect(method.getByRole("radio")).toHaveCount(2)
  expect(await undersizedInteractiveTargets(method)).toEqual([])
  await expect(method.getByText("현재 조건에서 검토가 끝난 상세 훈련이에요. 기록 없이 받는 방식과 비교해 고를 수 있어요.", { exact: true })).toBeVisible()
  expect((await method.locator("legend").boundingBox())!.height).toBeLessThanOrEqual(1)
  await summary.scrollIntoViewIfNeeded()
  await page.screenshot({ path: testInfo.outputPath("method-picker-normal.png") })
  const date = page.getByLabel("계획 시작 날짜", { exact: true })
  await date.fill("2026-09-10")
  await openMethodChoices()
  await method.getByRole("radio", { name: /5 × 1km @ 5K RP/u }).click()
  await expect(method.getByRole("radio", { name: /5 × 1km @ 5K RP/u })).toBeChecked()
  const save = page.getByRole("button", { name: /이 계획으로 시작하기/u })
  await expect(save).toBeDisabled()
  await method.getByRole("button", { name: "이 훈련으로 변경" }).click()
  const record = page.getByRole("region", { name: "개인 페이스 기준 기록" })
  await record.getByRole("group", { name: "기준 기록 선택" }).getByRole("button").first().click()
  await record.getByRole("button", { name: "이 기록으로 개인 페이스 적용" }).click()
  await expect(page.getByRole("heading", { name: "계획이 준비됐어요", exact: true })).toBeFocused()
  await openPlanOptions(page, true)
  await expect(save).toBeEnabled()
  await openMethodChoices()
  await method.getByRole("radio", { name: /기록 없이 시간·RPE로 받기/u }).click()
  await expect(method.getByRole("radio", { name: /기록 없이 시간·RPE로 받기/u })).toBeChecked()
  await expect(save).toBeDisabled()
  await method.getByRole("button", { name: "이 훈련으로 변경" }).click()
  await expect(record).toHaveCount(0)
  await expect(save).toBeEnabled()
  await openMethodChoices()
  await method.getByRole("radio", { name: /5 × 1km @ 5K RP/u }).check()
  await expect(save).toBeDisabled()
  await method.getByRole("button", { name: "이 훈련으로 변경" }).click()
  await expect(page.getByText(/5×1000m @5000m RP/u)).toHaveCount(0)
  await record.getByRole("button", { name: "이 기록으로 개인 페이스 적용" }).click()
  await expect(page.getByRole("heading", { name: "계획이 준비됐어요", exact: true })).toBeFocused()
  await openPlanOptions(page, true)
  await openMethodChoices()
  await expect(save).toBeEnabled()
  await expect(date).toHaveValue("2026-09-10")
  await page.locator("summary", { hasText: "A와 B는 뭐가 달라요?" }).click()
  const mainComparison = page.locator(".plan-main-comparison")
  await mainComparison.locator("summary").click()
  await expect(mainComparison.getByText("같은 핵심 훈련을 날짜와 전체 일정만 다르게 배치한 계획이에요. 서로 다른 훈련 두 개가 아니에요.")).toBeVisible()
  await expect(mainComparison.getByText(/^다른 부분:/u)).toHaveCount(0)
  await mainComparison.locator("section").first().scrollIntoViewIfNeeded()
  await page.screenshot({ path: testInfo.outputPath("main-method-comparison.png") })
  await mainComparison.locator("summary").click()
  const recommendation = page.getByRole("complementary", { name: "추천 페이스 기준" }).first()
  const recommendationToggle = recommendation.locator("summary")
  await expect(recommendationToggle).toBeVisible()
  await expect(recommendation.getByText(/오늘 컨디션·날씨에 따라 조절/u)).toBeVisible()
  await expect(recommendation.locator("details")).not.toHaveAttribute("open")
  expect((await recommendationToggle.boundingBox())!.height).toBeGreaterThanOrEqual(44)
  await recommendationToggle.scrollIntoViewIfNeeded()
  await page.screenshot({ path: testInfo.outputPath("pace-recommendation-collapsed.png") })
  await recommendationToggle.focus()
  await recommendationToggle.press("Enter")
  await expect(recommendation.locator("details")).toHaveAttribute("open")
  await expect(recommendation.getByText("1,111.25초 × 1000m ÷ 5000m")).toBeVisible()
  await expect(recommendation.getByText(/계산값 약 222.25초/u)).toBeVisible()
  await expect(recommendation.getByText(/휴식은 개인 기록에서 계산한 시간이 아니라/u)).toBeVisible()
  const recommendationFont = await recommendationToggle.evaluate(node => parseFloat(getComputedStyle(node).fontSize))
  const badgeFont = await recommendation.locator(".plan-pace-recommendation__badge").evaluate(node => parseFloat(getComputedStyle(node).fontSize))
  const normalFont = await summary.evaluate(node => parseFloat(getComputedStyle(node).fontSize))
  await page.evaluate(({ bodySize, captionSize }) => {
    document.documentElement.style.fontSize = "200%"
    document.documentElement.style.setProperty("--fs-body-sm", `${bodySize * 2}px`)
    document.documentElement.style.setProperty("--fs-caption", `${captionSize * 2}px`)
  }, { bodySize: recommendationFont, captionSize: badgeFont })
  expect(await summary.evaluate(node => parseFloat(getComputedStyle(node).fontSize))).toBeGreaterThanOrEqual(normalFont * 1.9)
  expect(await recommendationToggle.evaluate(node => parseFloat(getComputedStyle(node).fontSize))).toBeGreaterThanOrEqual(recommendationFont * 1.9)
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await expect.poll(() => recommendation.evaluate(node => node.scrollWidth <= node.clientWidth + 1)).toBe(true)
  await recommendationToggle.scrollIntoViewIfNeeded()
  await page.screenshot({ path: testInfo.outputPath("pace-recommendation-200pct.png") })
  const formula = recommendation.getByText("1,111.25초 × 1000m ÷ 5000m")
  await formula.scrollIntoViewIfNeeded()
  await expect(formula).toBeInViewport()
  await page.screenshot({ path: testInfo.outputPath("pace-recommendation-formula-200pct.png") })
  await recommendationToggle.press("Space")
  await expect(recommendation.locator("details")).not.toHaveAttribute("open")
  for (const option of await method.locator("label").all()) expect((await option.boundingBox())!.height).toBeGreaterThanOrEqual(44)
  await summary.scrollIntoViewIfNeeded()
  await page.screenshot({ path: testInfo.outputPath("method-picker-200pct.png") })
  await summary.press("Enter")
  await expect(method).not.toHaveAttribute("open")
  await save.click()
  await expect(page.getByRole("heading", { name: /9일 훈련 계획/u })).toBeVisible()
  const stored = await page.evaluate(() => JSON.parse(localStorage.getItem("trainoracle.plan-beta.v1")!))
  expect(stored.intake.startDate).toBe("2026-09-10")
  expect(stored.intake.trainingTimePreference).toBe("EVENING")
  expect(stored.intake.secondSessionMode).toBe("RECOVERY_PM_ALLOWED")
  const detailed = stored.activePlan.sessions.filter((session: { prescription: { kind: string } }) => session.prescription.kind === "PACE_TARGET")
  expect(detailed).toHaveLength(1)
  expect(detailed[0].prescription.targetRepSeconds).toBe(222.25)
  expect(detailed[0].prescription.templateId).toBe("V2-SEED-05")
  await page.reload()
  await page.getByRole("navigation", { name: "주 탭" }).getByRole("button", { name: "계획" }).click()
  await expect(page.getByRole("heading", { name: /9일 훈련 계획/u })).toBeVisible()
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem("trainoracle.plan-beta.v1")!).activePlan.candidateId)).toBe(stored.activePlan.candidateId)
  expect(errors).toEqual([])
})
