import { expect, test } from "@playwright/test"
import { selectNineDayProjection } from "./plan-flow"
import { undersizedInteractiveTargets } from "./touch-audit"

test.use({ serviceWorkers: "block" })

test("switches method in place and saves only the reconfirmed prescription", async ({ page }, testInfo) => {
  if (testInfo.project.name === "mobile-chromium") await page.setViewportSize({ width: 375, height: 667 })
  await page.clock.setFixedTime(new Date("2026-09-02T03:00:00.000Z"))
  const errors: string[] = []
  page.on("pageerror", error => errors.push(error.message))
  await page.addInitScript(() => {
    if (localStorage.getItem("trainoracle.athlete-records.v1") !== null) return
    localStorage.setItem("trainoracle.athlete-records.v1", JSON.stringify([{
      schemaVersion: 1, id: "00000000-0000-4000-8000-000000005001", purpose: "RECENT_RESULT",
      eventDistanceM: 5000, performanceSeconds: 1111.25, achievedOn: "2026-08-15", seasonId: null,
      enteredBy: "ATHLETE", verificationState: "SELF_REPORTED", sourceRef: "athlete-record:00000000-0000-4000-8000-000000005001",
      savedAt: "2026-08-15T12:00:00.000Z",
    }]))
  })
  await page.goto("/?app=1")
  await page.getByRole("navigation", { name: "주 탭" }).getByRole("button", { name: "계획" }).click()
  await page.getByRole("button", { name: /^5000m/u }).click()
  await page.getByRole("button", { name: /고등부/u }).click()
  await page.getByRole("button", { name: /구조화된 훈련과 경기 경험이 많아요/u }).click()
  await page.getByRole("button", { name: /통증은 없고 몸 상태는 평소와 같아요/u }).click()
  await page.getByRole("button", { name: "내 계획 완성하기" }).click()
  await page.getByRole("button", { name: /강한 유산소 반복.*VO₂/u }).click()
  const support = page.locator(".plan-support-coverage")
  const supportToggle = support.locator("summary")
  await expect(support).not.toHaveAttribute("open")
  await supportToggle.focus()
  await supportToggle.press("Enter")
  await expect(support).toHaveAttribute("open")
  await expect(support.getByRole("row")).toHaveCount(8)
  await expect(support.getByText("상세 훈련 준비 중", { exact: true })).toHaveCount(3)
  await expect(support.getByText("1000m 5회", { exact: true })).toBeVisible()
  expect((await supportToggle.boundingBox())!.height).toBeGreaterThanOrEqual(44)
  await supportToggle.scrollIntoViewIfNeeded()
  await page.screenshot({ path: testInfo.outputPath("support-coverage.png") })
  const middleSupportRow = support.getByRole("row", { name: /3000m/u })
  await middleSupportRow.scrollIntoViewIfNeeded()
  await expect(middleSupportRow).toBeInViewport({ ratio: 1 })
  await page.screenshot({ path: testInfo.outputPath("support-table-row.png") })
  const supportFont = await support.getByRole("table").evaluate(node => parseFloat(getComputedStyle(node).fontSize))
  await page.evaluate(size => document.documentElement.style.setProperty("--fs-body", `${size * 2}px`), supportFont)
  expect(await support.getByRole("table").evaluate(node => parseFloat(getComputedStyle(node).fontSize))).toBeGreaterThanOrEqual(supportFont * 1.9)
  await expect.poll(() => support.evaluate(node => node.scrollWidth <= node.clientWidth + 1)).toBe(true)
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await supportToggle.scrollIntoViewIfNeeded()
  await page.screenshot({ path: testInfo.outputPath("support-coverage-200pct.png") })
  await middleSupportRow.scrollIntoViewIfNeeded()
  await expect(middleSupportRow).toBeInViewport({ ratio: 1 })
  await page.screenshot({ path: testInfo.outputPath("support-table-row-200pct.png") })
  await page.evaluate(() => document.documentElement.style.removeProperty("--fs-body"))
  await supportToggle.press("Space")
  await expect(support).not.toHaveAttribute("open")
  await page.getByRole("button", { name: /RPE 기준으로 받기/u }).click()
  await page.getByRole("button", { name: /^3일/u }).click()
  await selectNineDayProjection(page)
  await page.getByRole("button", { name: /저녁에 운동해요/u }).click()
  await page.getByRole("button", { name: /하루 두 번 운동할게요/u }).click()
  await page.getByRole("button", { name: "날짜 없이 계획안 보기" }).click()
  const method = page.locator(".plan-method-picker")
  const summary = method.locator("summary")
  await expect(method).not.toHaveAttribute("open")
  await summary.focus()
  await summary.press("Enter")
  await expect(method).toHaveAttribute("open")
  await expect(method.getByRole("radio")).toHaveCount(2)
  expect(await undersizedInteractiveTargets(method)).toEqual([])
  await expect(method.getByText(/상세 방법은 현재 1개/u)).toBeVisible()
  expect((await method.locator("legend").boundingBox())!.height).toBeLessThanOrEqual(1)
  await summary.scrollIntoViewIfNeeded()
  await page.screenshot({ path: testInfo.outputPath("method-picker-normal.png") })
  const date = page.getByLabel("계획 시작 날짜", { exact: true })
  await date.fill("2026-09-10")
  await method.getByText("1000m 5회", { exact: true }).click()
  await expect(method.getByRole("radio", { name: /1000m 5회/u })).toBeChecked()
  const save = page.getByRole("button", { name: /시간 조절 계획 선택하기/u })
  await expect(save).toBeDisabled()
  const record = page.getByRole("region", { name: "개인 페이스 기준 기록" })
  await record.getByRole("group", { name: "기준 기록 선택" }).getByRole("button").first().click()
  await record.getByRole("button", { name: "이 기록으로 개인 페이스 적용" }).click()
  await expect(save).toBeEnabled()
  await method.getByText("시간·RPE 기준으로 받기", { exact: true }).click()
  await expect(method.getByRole("radio", { name: /시간·RPE 기준으로 받기/u })).toBeChecked()
  await expect(record).toHaveCount(0)
  await expect(save).toBeEnabled()
  await method.getByRole("radio", { name: /1000m 5회/u }).check()
  await expect(save).toBeDisabled()
  await expect(page.getByText(/5×1000m @5000m RP/u)).toHaveCount(0)
  await record.getByRole("button", { name: "이 기록으로 개인 페이스 적용" }).click()
  await expect(save).toBeEnabled()
  await expect(date).toHaveValue("2026-09-10")
  const recommendation = page.getByRole("complementary", { name: "추천 페이스 기준" }).first()
  const recommendationToggle = recommendation.locator("summary")
  await expect(recommendationToggle).toBeVisible()
  await expect(recommendation.getByText(/오늘 컨디션·날씨에 따라 조절/u)).toBeVisible()
  await expect(recommendation.locator("details")).not.toHaveAttribute("open")
  expect((await recommendationToggle.boundingBox())!.height).toBeGreaterThanOrEqual(44)
  await recommendationToggle.scrollIntoViewIfNeeded()
  await page.screenshot({ path: testInfo.outputPath("pace-recommendation-collapsed.png") })
  await recommendationToggle.focus()
  await recommendationToggle.press("Enter")
  await expect(recommendation.locator("details")).toHaveAttribute("open")
  await expect(recommendation.getByText("1,111.25초 × 1000m ÷ 5000m")).toBeVisible()
  await expect(recommendation.getByText(/계산값 약 222.25초/u)).toBeVisible()
  await expect(recommendation.getByText(/휴식은 개인 기록에서 계산한 시간이 아니라/u)).toBeVisible()
  const recommendationFont = await recommendationToggle.evaluate(node => parseFloat(getComputedStyle(node).fontSize))
  const badgeFont = await recommendation.locator(".plan-pace-recommendation__badge").evaluate(node => parseFloat(getComputedStyle(node).fontSize))
  const normalFont = await summary.evaluate(node => parseFloat(getComputedStyle(node).fontSize))
  await page.evaluate(({ bodySize, captionSize }) => {
    document.documentElement.style.fontSize = "200%"
    document.documentElement.style.setProperty("--fs-body-sm", `${bodySize * 2}px`)
    document.documentElement.style.setProperty("--fs-caption", `${captionSize * 2}px`)
  }, { bodySize: recommendationFont, captionSize: badgeFont })
  expect(await summary.evaluate(node => parseFloat(getComputedStyle(node).fontSize))).toBeGreaterThanOrEqual(normalFont * 1.9)
  expect(await recommendationToggle.evaluate(node => parseFloat(getComputedStyle(node).fontSize))).toBeGreaterThanOrEqual(recommendationFont * 1.9)
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await expect.poll(() => recommendation.evaluate(node => node.scrollWidth <= node.clientWidth + 1)).toBe(true)
  await recommendationToggle.scrollIntoViewIfNeeded()
  await page.screenshot({ path: testInfo.outputPath("pace-recommendation-200pct.png") })
  const formula = recommendation.getByText("1,111.25초 × 1000m ÷ 5000m")
  await formula.scrollIntoViewIfNeeded()
  await expect(formula).toBeInViewport()
  await page.screenshot({ path: testInfo.outputPath("pace-recommendation-formula-200pct.png") })
  await recommendationToggle.press("Space")
  await expect(recommendation.locator("details")).not.toHaveAttribute("open")
  for (const option of await method.locator("label").all()) expect((await option.boundingBox())!.height).toBeGreaterThanOrEqual(44)
  await summary.scrollIntoViewIfNeeded()
  await page.screenshot({ path: testInfo.outputPath("method-picker-200pct.png") })
  await summary.press("Enter")
  await expect(method).not.toHaveAttribute("open")
  await save.click()
  await expect(page.getByRole("heading", { name: /9일 훈련 계획/u })).toBeVisible()
  const stored = await page.evaluate(() => JSON.parse(localStorage.getItem("trainoracle.plan-beta.v1")!))
  expect(stored.intake.startDate).toBe("2026-09-10")
  expect(stored.intake.trainingTimePreference).toBe("EVENING")
  expect(stored.intake.secondSessionMode).toBe("RECOVERY_PM_ALLOWED")
  const detailed = stored.activePlan.sessions.filter((session: { prescription: { kind: string } }) => session.prescription.kind === "PACE_TARGET")
  expect(detailed).toHaveLength(1)
  expect(detailed[0].prescription.targetRepSeconds).toBe(222.25)
  expect(detailed[0].prescription.templateId).toBe("V2-SEED-05")
  await page.reload()
  await page.getByRole("navigation", { name: "주 탭" }).getByRole("button", { name: "계획" }).click()
  await expect(page.getByRole("heading", { name: /9일 훈련 계획/u })).toBeVisible()
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem("trainoracle.plan-beta.v1")!).activePlan.candidateId)).toBe(stored.activePlan.candidateId)
  expect(errors).toEqual([])
})
