import { expect, test } from "@playwright/test"
import { selectNineDayProjection } from "./plan-flow"

test.use({ serviceWorkers: "block" })

test("switches method in place and saves only the reconfirmed prescription", async ({ page }, testInfo) => {
  if (testInfo.project.name === "mobile-chromium") await page.setViewportSize({ width: 375, height: 667 })
  await page.clock.setFixedTime(new Date("2026-09-02T03:00:00.000Z"))
  const errors: string[] = []
  page.on("pageerror", error => errors.push(error.message))
  await page.addInitScript(() => {
    if (localStorage.getItem("trainoracle.athlete-records.v1") !== null) return
    localStorage.setItem("trainoracle.athlete-records.v1", JSON.stringify([{
      schemaVersion: 1, id: "00000000-0000-4000-8000-000000005001", purpose: "RECENT_RESULT",
      eventDistanceM: 5000, performanceSeconds: 1111.25, achievedOn: "2026-08-15", seasonId: null,
      enteredBy: "ATHLETE", verificationState: "SELF_REPORTED", sourceRef: "athlete-record:00000000-0000-4000-8000-000000005001",
      savedAt: "2026-08-15T12:00:00.000Z",
    }]))
  })
  await page.goto("/?app=1")
  await page.getByRole("navigation", { name: "주 탭" }).getByRole("button", { name: "계획" }).click()
  await page.getByRole("button", { name: /^5000m/u }).click()
  await page.getByRole("button", { name: /고등부/u }).click()
  await page.getByRole("button", { name: /구조화된 훈련과 경기 경험이 많아요/u }).click()
  await page.getByRole("button", { name: /통증은 없고 몸 상태는 평소와 같아요/u }).click()
  await page.getByRole("button", { name: "내 계획 완성하기" }).click()
  await page.getByRole("button", { name: /강한 유산소 반복.*VO₂/u }).click()
  await page.getByRole("button", { name: /RPE 기준으로 받기/u }).click()
  await page.getByRole("button", { name: /^3일/u }).click()
  await selectNineDayProjection(page)
  await page.getByRole("button", { name: /저녁에 운동해요/u }).click()
  await page.getByRole("button", { name: /하루 두 번 운동할게요/u }).click()
  await page.getByRole("button", { name: "날짜 없이 계획안 보기" }).click()
  const method = page.locator(".plan-method-picker")
  const summary = method.locator("summary")
  await expect(method).not.toHaveAttribute("open")
  await summary.focus()
  await summary.press("Enter")
  await expect(method).toHaveAttribute("open")
  await expect(method.getByRole("radio")).toHaveCount(2)
  await expect(method.getByText(/상세 방법은 현재 1개/u)).toBeVisible()
  expect((await method.locator("legend").boundingBox())!.height).toBeLessThanOrEqual(1)
  await summary.scrollIntoViewIfNeeded()
  await page.screenshot({ path: testInfo.outputPath("method-picker-normal.png") })
  const date = page.getByLabel("계획 시작 날짜", { exact: true })
  await date.fill("2026-09-10")
  await method.getByRole("radio", { name: /1000m 5회/u }).check()
  const save = page.getByRole("button", { name: /시간 조절 계획 선택하기/u })
  await expect(save).toBeDisabled()
  const record = page.getByRole("region", { name: "개인 페이스 기준 기록" })
  await record.getByRole("group", { name: "기준 기록 선택" }).getByRole("button").first().click()
  await record.getByRole("button", { name: "이 기록으로 개인 페이스 적용" }).click()
  await expect(save).toBeEnabled()
  await method.getByRole("radio", { name: /시간·RPE 기준으로 받기/u }).check()
  await expect(record).toHaveCount(0)
  await expect(save).toBeEnabled()
  await method.getByRole("radio", { name: /1000m 5회/u }).check()
  await expect(save).toBeDisabled()
  await expect(page.getByText(/5×1000m @5000m RP/u)).toHaveCount(0)
  await record.getByRole("button", { name: "이 기록으로 개인 페이스 적용" }).click()
  await expect(save).toBeEnabled()
  await expect(date).toHaveValue("2026-09-10")
  const normalFont = await summary.evaluate(node => parseFloat(getComputedStyle(node).fontSize))
  await page.evaluate(() => { document.documentElement.style.fontSize = "200%" })
  expect(await summary.evaluate(node => parseFloat(getComputedStyle(node).fontSize))).toBeGreaterThanOrEqual(normalFont * 1.9)
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  for (const option of await method.locator("label").all()) expect((await option.boundingBox())!.height).toBeGreaterThanOrEqual(44)
  await summary.scrollIntoViewIfNeeded()
  await page.screenshot({ path: testInfo.outputPath("method-picker-200pct.png") })
  await summary.press("Enter")
  await expect(method).not.toHaveAttribute("open")
  await save.click()
  await expect(page.getByRole("heading", { name: /9일 훈련 계획/u })).toBeVisible()
  const stored = await page.evaluate(() => JSON.parse(localStorage.getItem("trainoracle.plan-beta.v1")!))
  expect(stored.intake.startDate).toBe("2026-09-10")
  expect(stored.intake.trainingTimePreference).toBe("EVENING")
  expect(stored.intake.secondSessionMode).toBe("RECOVERY_PM_ALLOWED")
  const detailed = stored.activePlan.sessions.filter((session: { prescription: { kind: string } }) => session.prescription.kind === "PACE_TARGET")
  expect(detailed).toHaveLength(1)
  expect(detailed[0].prescription.targetRepSeconds).toBe(222.25)
  expect(detailed[0].prescription.templateId).toBe("V2-SEED-05")
  await page.reload()
  await page.getByRole("navigation", { name: "주 탭" }).getByRole("button", { name: "계획" }).click()
  await expect(page.getByRole("heading", { name: /9일 훈련 계획/u })).toBeVisible()
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem("trainoracle.plan-beta.v1")!).activePlan.candidateId)).toBe(stored.activePlan.candidateId)
  expect(errors).toEqual([])
})
