import { test, expect, type Page } from "@playwright/test"
import { loadCatalogReductionFixture } from "./fixtures/catalog-cycle-reduction-loader"
import { JOURNAL_STORAGE_KEY } from "../src/domain/journal-storage-keys"

async function openPlan(page: Page) {
  await page.getByRole("navigation", { name: "주 탭" }).getByRole("button", { name: "훈련", exact: true }).click()
}
async function storedPlan(page: Page) {
  return page.evaluate(() => JSON.parse(localStorage.getItem("trainoracle.plan-beta.v1") ?? "null"))
}
async function generate(page: Page, event = "5000", experienced = false) {
  await page.clock.setFixedTime(new Date("2026-10-02T03:00:00Z"))
  await page.goto("/?app=1")
  await openPlan(page)
  await page.getByRole("combobox", { name: "종목", exact: true }).selectOption(event)
  await page.getByLabel("분", { exact: true }).fill(event === "800" ? "2" : "18")
  await page.getByLabel("초", { exact: true }).fill(event === "800" ? "1.5" : "31.5")
  await page.getByLabel("기록 달성일", { exact: true }).fill("2026-09-25")
  await page.getByRole("button", { name: "내 계획 받기", exact: true }).click()
  if (experienced) await page.getByRole("button", { name: /구조화된 훈련/ }).click()
  else await page.getByRole("button", { name: /훈련 계획에 맞춰 달려 본 경험/ }).click()
  await page.getByRole("button", { name: /^3일/ }).click()
  await page.getByRole("button", { name: /통증은 없고 몸 상태는 평소와 같아요/ }).click()
}

for (const outcome of ["PARTIAL", "COMPLETED"] as const) test(`edited MAIN -> ${outcome} journal -> next cycle`, async ({ page }, info) => {
  const errors: string[] = []
  page.on("pageerror", error => errors.push(error.message))
  await generate(page)
  await page.getByRole("button", { name: "이 일정으로 시작", exact: true }).click()
  await expect(page.getByRole("heading", { name: "9일 훈련 계획", exact: true })).toBeVisible()
  const original = await storedPlan(page)
  const main = original.activePlan.sessions.find((s: { role: string }) => s.role === "QUALITY")
  expect(main.prescription.catalogWorkout.catalogId).toBe("P-RHYTHM-T")
  await page.locator("[data-plan-edit-button]").click()
  await page.getByRole("button", { name: "훈련 내용 바꾸기", exact: true }).click()
  const editor = page.getByRole("region", { name: "이 훈련 수정" })
  await editor.getByLabel("수정할 훈련").selectOption(`${main.day}:${main.slot}`)
  await editor.getByRole("checkbox", { name: "이 훈련은 아직 시작하지 않았어요." }).check()
  await editor.getByRole("combobox", { name: "훈련 구성", exact: true }).selectOption("P-RHYTHM-TS")
  const longer = editor.getByRole("checkbox", { name: /긴 구성임을 확인하고 동의/ })
  if (await longer.count()) await longer.check()
  await editor.getByRole("button", { name: "이 구성으로 바꾸기", exact: true }).click()
  await editor.getByRole("button", { name: "변경안 미리보기", exact: true }).click()
  await expect(editor.getByRole("heading", { name: "변경안 미리보기" })).toBeVisible()
  await editor.getByRole("checkbox", { name: "지금 통증이나 몸 상태 이상이 없어요." }).check()
  await editor.getByRole("button", { name: "변경안 적용하기", exact: true }).click()
  await expect(page.getByRole("heading", { name: "9일 훈련 계획", exact: true })).toBeVisible()
  await page.reload()
  await openPlan(page)
  const changed = await storedPlan(page)
  expect(changed.activePlan.candidateId).not.toBe(original.activePlan.candidateId)
  expect(changed.activePlan.sessions.find((s: { day: number; slot: string }) => s.day === main.day && s.slot === main.slot)
    .prescription.catalogWorkout.catalogId).toBe("P-RHYTHM-TS")
  await page.clock.setFixedTime(new Date("2026-10-06T03:00:00Z"))
  await page.reload()
  await openPlan(page)
  await page.getByRole("button", { name: /2026년 10월 6일 화요일/ }).click()
  await page.getByText("일지·진행 기록", { exact: true }).click()
  await page.getByRole("button", { name: "이 훈련 일지 쓰기", exact: true }).click()
  await page.getByRole("button", { name: outcome === "PARTIAL" ? "일부만 했거나 내용을 바꿨어요" : "계획대로 마쳤어요", exact: true }).click()
  await page.getByRole("button", { name: "오전", exact: true }).click()
  await page.getByRole("button", { name: /^RPE 7,/ }).click()
  await page.getByRole("button", { name: "없어요", exact: true }).click()
  if (outcome === "PARTIAL") await page.getByRole("button", { name: "횟수를 줄였어요" }).click()
  await page.getByRole("button", { name: "이대로 저장", exact: true }).click()
  await expect(page.getByRole("heading", { name: "오늘 기록을 남겼어요.", exact: true })).toBeVisible()
  if (outcome === "COMPLETED") {
    await page.getByRole("button", { name: "이 결과를 계획에도 반영" }).click()
    await expect(page.getByText("일지의 결과를 계획에도 반영했어요.", { exact: true })).toBeVisible()
    expect((await storedPlan(page)).progress).toContainEqual({ sessionDay: main.day, sessionSlot: main.slot, state: "COMPLETED" })
  } else {
    await expect(page.getByRole("button", { name: "이 결과를 계획에도 반영" })).toHaveCount(0)
    expect((await storedPlan(page)).progress).toEqual([])
  }
  await page.getByRole("button", { name: "완료", exact: true }).click()
  await openPlan(page)
  await expect(page.getByText(outcome === "PARTIAL" ? "일부 수행·변경 기록 있음" : "수행 기록 있음", { exact: true }).first()).toBeVisible()
  const activeCard = page.locator('.plan-schedule-preview > li[data-active-card="true"]')
  await activeCard.getByRole("button", { name: "연결된 일지 기록 보기", exact: true }).click()
  await expect(page.getByRole("tabpanel")).toContainText("직접 기록한 RPE 7")
  await page.screenshot({ path: info.outputPath("edited-main-journal.png"), fullPage: true, animations: "disabled" })
  await page.getByRole("button", { name: "훈련과 일지로 돌아가기", exact: true }).click()
  await page.getByRole("navigation", { name: "주 탭" }).getByRole("button", { name: "홈", exact: true }).click()
  await page.getByRole("button", { name: /2026년 10월 6일 기록 1개 보기/ }).click()
  await page.getByText("계획한 훈련과 비교하기", { exact: true }).click()
  await expect(page.getByRole("heading", { name: "당시 계획한 훈련 방법" })).toBeVisible()
  if (outcome === "PARTIAL") await expect(page.getByText("내가 남긴 변경: 횟수를 줄였어요", { exact: true })).toBeVisible()
  await page.screenshot({ path: info.outputPath("original-journal.png"), fullPage: true, animations: "disabled" })
  await page.clock.setFixedTime(new Date("2026-10-11T03:00:00Z"))
  await page.reload()
  await openPlan(page)
  await page.getByRole("button", { name: "현재 기준으로 다음 계획안 만들기", exact: true }).click()
  await page.getByRole("button", { name: /통증은 없고 몸 상태는 평소와 같아요/ }).click()
  await expect(page.getByRole("region", { name: "이전 수행 반영" })).toContainText(outcome === "PARTIAL"
    ? "다르게 수행한 기록" : "수행 기록이 한 번뿐이라")
  await page.getByRole("button", { name: "이 일정으로 시작", exact: true }).click()
  await expect(page.getByRole("heading", { name: "9일 훈련 계획", exact: true })).toBeVisible()
  const successor = await storedPlan(page)
  expect(successor.intake.startDate).toBe("2026-10-11")
  expect(successor.activePlan.candidateId).not.toBe(changed.activePlan.candidateId)
  const nextMain = successor.activePlan.sessions.find((s: { role: string }) => s.role === "QUALITY")
  expect(nextMain.prescription.catalogWorkout.catalogId).toBe("P-RHYTHM-TS")
  expect(errors).toEqual([])
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false)
  await page.screenshot({ path: info.outputPath("next-cycle.png"), fullPage: true, animations: "disabled" })
  await page.getByRole("navigation", { name: "주 탭" }).getByRole("button", { name: "홈", exact: true }).click()
  await page.getByRole("button", { name: /2026년 10월 6일 기록 1개 보기/ }).click()
  await page.getByText("계획한 훈련과 비교하기", { exact: true }).click()
  await expect(page.getByText("그때 보관한 계획의 훈련이에요.", { exact: true })).toBeVisible()
  if (outcome === "PARTIAL") await expect(page.getByText("내가 남긴 변경: 횟수를 줄였어요", { exact: true })).toBeVisible()
  expect(errors).toEqual([])
})

test("first numeric pace plan routes its primary action to explicit record confirmation", async ({ page }) => {
  await generate(page, "800", true)
  await expect(page.getByText("처방 기준 · 기록 확인 전 · 페이스 초안", { exact: true })).toBeVisible()
  await page.getByRole("button", { name: "기준 기록 확인하기", exact: true }).click()
  await expect(page.getByRole("region", { name: "개인 페이스 기준 기록" })).toBeVisible()
  await page.getByRole("button", { name: "이 기록으로 개인 페이스 적용", exact: true }).click()
  await page.getByRole("button", { name: "이 일정으로 시작", exact: true }).click()
  await expect(page.getByRole("heading", { name: "9일 훈련 계획", exact: true })).toBeVisible()
  await expect(page.getByText("처방 기준 · 기록 기준 페이스 · 주요 훈련 1회", { exact: true })).toBeVisible()
  const main = (await storedPlan(page)).activePlan.sessions.find((s: { prescription: { kind: string } }) => s.prescription.kind === "PACE_TARGET")
  expect(main.prescription.targetRepSeconds).toBe(30.375)
})

test("repeated above-range journals explain and apply only the reviewed shorter successor", async ({ page }, info) => {
  const fixture = loadCatalogReductionFixture()
  await page.clock.setFixedTime(new Date("2026-10-01T03:00:00Z"))
  await page.goto("/?app=1")
  await page.evaluate(({ fixture, key }) => {
    localStorage.setItem("trainoracle.plan-beta.v1", JSON.stringify(fixture.state))
    localStorage.setItem(key, JSON.stringify(fixture.journals))
  }, { fixture, key: JOURNAL_STORAGE_KEY })
  await page.reload()
  await openPlan(page)
  await page.getByRole("button", { name: "현재 기준으로 다음 계획안 만들기", exact: true }).click()
  await page.getByRole("button", { name: /통증은 없고 몸 상태는 평소와 같아요/ }).click()
  const explanation = page.getByRole("region", { name: "이전 수행 반영" })
  await expect(explanation).toContainText("계획보다 높은 체감 강도가 2회")
  await expect(explanation).toContainText("양이 적은 같은 방식")
  await page.screenshot({ path: info.outputPath("reduction-reason.png"), fullPage: true, animations: "disabled" })
  await page.getByRole("button", { name: "이 일정으로 시작", exact: true }).click()
  await expect(page.getByRole("heading", { name: "10일 훈련 계획", exact: true })).toBeVisible()
  const saved = await storedPlan(page)
  const main = saved.activePlan.sessions.filter((s: { role: string }) => s.role === "QUALITY")
  expect(main.map((s: { prescription: { catalogWorkout: { catalogId: string } } }) => s.prescription.catalogWorkout.catalogId)).toEqual(["P-LT-B-480", "P-LT-B-480"])
  expect(saved.activePlan.candidateId).not.toBe(fixture.state.activePlan.candidateId)
  await page.reload()
  expect((await storedPlan(page)).activePlan.candidateId).toBe(saved.activePlan.candidateId)
  expect(await page.evaluate(key => JSON.parse(localStorage.getItem(key) ?? "[]"), JOURNAL_STORAGE_KEY)).toEqual(fixture.journals)
})

for (const reason of ["old-pain", "unconfirmed"] as const) test(`high RPE with ${reason} does not change next-cycle dose`, async ({ page }) => {
  const fixture = loadCatalogReductionFixture()
  const journals = fixture.journals.map(entry => reason === "old-pain"
    ? { ...entry, painCheckStatus: "SIGNAL_REPORTED" }
    : { ...entry, activityOutcome: undefined, activitySlot: undefined })
  await page.clock.setFixedTime(new Date("2026-10-01T03:00:00Z"))
  await page.goto("/?app=1")
  await page.evaluate(({ state, journals, key }) => {
    localStorage.setItem("trainoracle.plan-beta.v1", JSON.stringify(state))
    localStorage.setItem(key, JSON.stringify(journals))
  }, { state: fixture.state, journals, key: JOURNAL_STORAGE_KEY })
  await page.reload()
  await openPlan(page)
  await page.getByRole("button", { name: "현재 기준으로 다음 계획안 만들기", exact: true }).click()
  await page.getByRole("button", { name: /통증은 없고 몸 상태는 평소와 같아요/ }).click()
  await expect(page.getByRole("region", { name: "이전 수행 반영" })).toContainText(reason === "old-pain"
    ? "통증을 남긴 기록이 포함돼" : "모두 확인하지 못해 훈련량을 바꾸지 않았어요")
  await page.getByRole("button", { name: "이 일정으로 시작", exact: true }).click()
  await expect(page.getByRole("heading", { name: "10일 훈련 계획", exact: true })).toBeVisible()
  const saved = await storedPlan(page)
  expect(saved.activePlan.sessions.filter((s: { role: string }) => s.role === "QUALITY")
    .map((s: { prescription: { catalogWorkout: { catalogId: string } } }) => s.prescription.catalogWorkout.catalogId))
    .toEqual(["P-LT-B", "P-LT-B"])
})
