import { expect, test, type Page } from "@playwright/test"

test.use({ serviceWorkers: "block" })
test.beforeEach(async ({ page, baseURL }) => {
  const origin = new URL(baseURL!).origin
  await page.route("**/*", route => new URL(route.request().url()).origin === origin ? route.continue() : route.abort())
  await page.goto("/?app=1&uitest=1")
  await page.evaluate(() => { localStorage.clear(); sessionStorage.clear() })
  await page.reload()
})

async function openProfile(page: Page) {
  await page.getByRole("button", { name: "더보기", exact: true }).click()
  await page.getByRole("button", { name: "러닝 취향", exact: false }).click()
  await expect(page.getByRole("heading", { name: "나는 어떤 달리기를 좋아할까요?" })).toBeVisible()
}

test("preference questions, reactive helper and optional next topic retain answers at 375px", async ({ page }, info) => {
  await page.setViewportSize({ width: 375, height: 812 })
  await openProfile(page)
  const helper = page.getByRole("button", { name: "마리의 답변 팁" })
  await expect.poll(() => helper.locator("img").evaluate(node => (node as HTMLImageElement).naturalWidth)).toBe(256)
  await helper.focus()
  await page.keyboard.press("Enter")
  await expect(helper).toHaveAttribute("aria-expanded", "true")
  await expect(helper.locator("img")).toHaveAttribute("src", /mari-profile-wave-v4.webp$/u)
  await expect(page.getByText("정답은 없어요. 평소 내 모습에 가까운 답을 골라요.")).toBeVisible()
  await page.keyboard.press("Escape")
  await expect(helper).toHaveAttribute("aria-expanded", "false")
  await page.screenshot({ path: info.outputPath("profile-entry-375.png") })
  await page.getByRole("button", { name: "내 훈련 방식 알아보기 · 질문 3개", exact: true }).click()
  const dialog = page.getByRole("dialog", { name: "계획 선호", exact: true })
  await expect(dialog.getByRole("heading", { name: "달리기 전에 할 내용을 정해두는 것이 좋아요." })).toBeFocused()
  await dialog.getByRole("button", { name: "매우 그래요", exact: true }).click()
  await expect(dialog.getByRole("heading", { name: "훈련 순서가 미리 정해져 있으면 마음이 편해요." })).toBeFocused()
  await dialog.getByRole("button", { name: "이전 질문", exact: true }).click()
  await expect(dialog.getByRole("button", { name: "매우 그래요", exact: true })).toHaveAttribute("aria-pressed", "true")
  await page.screenshot({ path: info.outputPath("profile-question-375.png"), animations: "disabled" })
  for (let n = 0; n < 3; n++) await dialog.getByRole("button", { name: "매우 그래요", exact: true }).click()
  await expect(dialog.getByRole("heading", { name: "내 답을 정리했어요" })).toBeFocused()
  await expect(dialog.locator(".oracle-v2__result-number")).toContainText("100")
  await expect(dialog.getByText("취향을 정리한 값이에요. 체력이나 실력 점수가 아니에요.")).toBeVisible()
  await expect(dialog.getByRole("button", { name: "기록 도전도 알아보기", exact: true })).toBeEnabled()
  const resultHelper = dialog.getByRole("button", { name: "계획을 챙기는 여우 캐릭터 이야기" })
  await resultHelper.click()
  await page.keyboard.press("Escape")
  await expect(dialog).toBeVisible()
  await expect(resultHelper).toHaveAttribute("aria-expanded", "false")
  await page.screenshot({ path: info.outputPath("profile-result-375.png") })
  await dialog.getByText("내 답 확인·수정", { exact: true }).click()
  await dialog.getByRole("button", { name: /달리기 전에 할 내용을 정해두는 것이 좋아요./u }).click()
  await dialog.getByRole("button", { name: "그런 편이에요", exact: true }).click()
  await expect(dialog.getByRole("heading", { name: "내 답을 정리했어요" })).toBeFocused()
  await expect(dialog.locator(".oracle-v2__result-number")).toContainText("90")
  await dialog.getByRole("button", { name: "기록 도전도 알아보기", exact: true }).click()
  await expect(page.getByRole("dialog", { name: "기록 도전 선호" }).getByRole("heading", { name: "내가 세운 기록 목표에 도전하는 일이 즐거워요." })).toBeFocused()
  await page.goBack()
  await expect(page.getByRole("dialog")).toHaveCount(0)
  await expect(page.getByRole("button", { name: "계획, 90점, 결과 보기", exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(await page.evaluate(() => JSON.stringify(history.state))).not.toMatch(/STRUCTURE_[123]|CHALLENGE_[123]/u)
})

test("large text, missing pictures and app motion preference keep answers usable at 320px", async ({ page }, info) => {
  await page.setViewportSize({ width: 320, height: 740 })
  await page.route("**/mari-profile-*-v4.webp", route => route.abort())
  await page.evaluate(() => {
    localStorage.setItem("trainoracle.calendar-reduced-motion.v1", "true")
    window.dispatchEvent(new StorageEvent("storage", { key: "trainoracle.calendar-reduced-motion.v1" }))
  })
  await openProfile(page)
  await page.getByRole("button", { name: "마리의 답변 팁" }).click()
  await expect(page.getByText("정답은 없어요. 평소 내 모습에 가까운 답을 골라요.")).toBeVisible()
  await page.getByRole("button", { name: "내 훈련 방식 알아보기 · 질문 3개", exact: true }).click()
  const dialog = page.getByRole("dialog", { name: "계획 선호", exact: true })
  await expect(dialog.locator(".oracle-v2__question")).toHaveCSS("animation-name", "none")
  await page.addStyleTag({ content: ".oracle-v2.oracle-v2__dialog .app-heading.app-heading--screen {font-size:48px} .oracle-v2__dialog p,.oracle-v2__dialog button,.oracle-v2__dialog summary {font-size:28px}" })
  await expect(dialog.getByRole("heading", { level: 1 })).toHaveCSS("font-size", "48px")
  const choice = dialog.getByRole("button", { name: "그런 편이에요", exact: true })
  expect((await choice.boundingBox())!.height).toBeGreaterThanOrEqual(44)
  expect(await dialog.locator(".oracle-v2__reader-body").evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true)
  await page.screenshot({ path: info.outputPath("profile-large-320.png") })
  await choice.focus()
  await page.keyboard.press("Enter")
  await expect(dialog.getByRole("heading", { name: "훈련 순서가 미리 정해져 있으면 마음이 편해요." })).toBeFocused()
  await dialog.getByRole("button", { name: "닫기", exact: true }).click()
  await page.getByRole("button", { name: "작성하던 답 이어가기", exact: true }).click()
  await expect(dialog.getByRole("heading", { name: "훈련 순서가 미리 정해져 있으면 마음이 편해요." })).toBeFocused()
  await dialog.getByRole("button", { name: "이전 질문", exact: true }).click()
  await expect(dialog.getByRole("button", { name: "그런 편이에요", exact: true })).toHaveAttribute("aria-pressed", "true")
})

test("desktop skip keeps an unknown result distinct from zero", async ({ page }, info) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.emulateMedia({ reducedMotion: "reduce" })
  await openProfile(page)
  await page.getByRole("button", { name: "내 훈련 방식 알아보기 · 질문 3개", exact: true }).click()
  const dialog = page.getByRole("dialog", { name: "계획 선호", exact: true })
  await expect(dialog.locator(".oracle-v2__question")).toHaveCSS("animation-name", "none")
  for (let n = 0; n < 3; n++) await dialog.getByRole("button", { name: "건너뛰기", exact: true }).click()
  await expect(dialog.getByText("점수 없이 답만 정리했어요.", { exact: true })).toBeVisible()
  await expect(dialog.locator(".oracle-v2__result-number")).toHaveCount(0)
  await page.screenshot({ path: info.outputPath("profile-skipped-desktop.png") })
})
