import { expect, test } from "@playwright/test"

test.use({ serviceWorkers: "block" })

for (const width of [320, 375, 1440]) {
  test(`record reading and together flow at ${width}px`, async ({ page }, testInfo) => {
    await page.setViewportSize({ width, height: width === 1440 ? 900 : 780 })
    await page.goto("/?app=1")
    await page.getByRole("button", { name: "더보기", exact: true }).click()
    await page.getByRole("button", { name: "최고기록으로 풀이하기", exact: true }).click()
    await page.getByRole("button", { name: "5000m", exact: true }).click()
    await page.getByRole("textbox", { name: "최고기록" }).fill("20:30")
    await page.getByRole("button", { name: "나의 러닝 풀이 보기" }).click()
    await expect(page.getByRole("heading", { name: "5000m에 담긴 나의 리듬" })).toBeVisible()
    await expect(page.getByText("4분 6초", { exact: true })).toBeVisible()
    await expect(page.locator(".record-reading__signature img")).toHaveJSProperty("complete", true)
    expect(await page.locator(".record-reading__signature img").evaluate(image => (image as HTMLImageElement).naturalWidth)).toBeGreaterThan(0)
    await expect(page.locator("html")).toHaveJSProperty("scrollWidth", width)
    await page.waitForTimeout(300)
    await page.screenshot({ path: testInfo.outputPath(`reading-${width}.png`) })

    await page.goBack()
    await expect(page.getByRole("textbox", { name: "최고기록" })).toHaveValue("20:30")
    await page.getByRole("button", { name: "나의 러닝 풀이 보기" }).click()
    await page.getByRole("button", { name: "친구와 러닝 궁합 보기" }).click()
    await page.getByRole("button", { name: "5000m", exact: true }).click()
    await page.getByRole("textbox", { name: "최고기록" }).fill("21:40")
    const compare = page.getByRole("button", { name: "친구 기록과 비교하기" })
    await expect(compare).toBeDisabled()
    await expect(page.getByText("동의를 확인하면 풀이를 볼 수 있어요.")).toBeVisible()
    await page.getByRole("checkbox", { name: /친구가 이 기록/u }).check()
    await expect(compare).toBeEnabled()
    await compare.click()
    await expect(page.getByRole("heading", { name: "같은 거리, 서로 다른 리듬" })).toBeVisible()
    await expect(page.getByText(/차이는 1분 10초예요/u)).toBeVisible()
    await expect(page.locator("html")).toHaveJSProperty("scrollWidth", width)
    await page.waitForTimeout(300)
    await page.screenshot({ path: testInfo.outputPath(`together-${width}.png`) })
    await page.getByRole("group", { name: "풀이 내용" }).getByRole("button", { name: "러닝 궁합", exact: true }).click()
    await expect(page.getByRole("heading", { name: "본운동은 각자의 리듬" })).toBeVisible()
    expect(await page.evaluate(() => JSON.stringify(history.state))).not.toMatch(/20:30|21:40|"seconds"|"achievedOn"/u)
    await page.getByRole("button", { name: "풀이 닫기" }).click()
    await expect(page.getByRole("heading", { name: "더보기", exact: true })).toBeVisible()
    await page.getByRole("button", { name: "최고기록으로 풀이하기" }).click()
    await expect(page.getByRole("heading", { name: "어떤 기록을 풀어볼까요?" })).toBeVisible()
  })
}

test("different events, reduced motion, text zoom and edited input", async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 812 })
  await page.emulateMedia({ reducedMotion: "reduce" })
  await page.goto("/?app=1")
  await page.getByRole("button", { name: "더보기", exact: true }).click()
  await page.getByRole("button", { name: "최고기록으로 풀이하기", exact: true }).click()
  await page.getByRole("button", { name: "800m", exact: true }).click()
  await page.getByRole("textbox", { name: "최고기록" }).fill("2:02.5")
  await page.getByRole("button", { name: "나의 러닝 풀이 보기" }).click()
  await expect(page.getByText("2분 33.13초", { exact: true })).toBeVisible()
  await page.getByRole("button", { name: "친구와 러닝 궁합 보기" }).click()
  await page.getByRole("button", { name: "마라톤", exact: true }).click()
  await page.getByRole("textbox", { name: "최고기록" }).fill("3:45:30")
  await page.getByRole("checkbox", { name: /친구가 이 기록/u }).check()
  await page.getByRole("button", { name: "친구 기록과 비교하기" }).click()
  await expect(page.getByRole("heading", { name: "다른 무대, 함께 달릴 시간" })).toBeVisible()
  await expect(page.getByRole("img", { name: /같은 종목 기록/u })).toHaveCount(0)
  await expect(page.getByText(/환산하지 않았어요/u)).toBeVisible()
  await page.evaluate(() => {
    document.querySelectorAll<HTMLElement>(".record-reading h1, .record-reading p, .record-reading button, .record-reading strong, .record-reading small, .record-reading span").forEach(element => {
      element.style.fontSize = `${parseFloat(getComputedStyle(element).fontSize) * 2}px`
    })
  })
  await expect(page.locator("html")).toHaveJSProperty("scrollWidth", 375)
  await page.getByRole("button", { name: "친구 기록 바꿔보기" }).click()
  await page.getByRole("textbox", { name: "최고기록" }).fill("4:00:00")
  await expect(page.getByRole("checkbox", { name: /친구가 이 기록/u })).not.toBeChecked()
  await page.getByRole("checkbox", { name: /친구가 이 기록/u }).check()
  await page.getByRole("button", { name: "친구 기록과 비교하기" }).click()
  await expect(page.getByText("4시간 0분 0초", { exact: true })).toBeVisible()
})

test("friend-first reading keeps ownership and browser Forward after close cannot recover input", async ({ page }) => {
  await page.goto("/?app=1")
  await page.getByRole("button", { name: "더보기", exact: true }).click()
  await page.getByRole("button", { name: "최고기록으로 풀이하기", exact: true }).click()
  await page.getByRole("button", { name: "친구 기록", exact: true }).click()
  await expect(page.getByRole("group", { name: "친구 종목" })).toBeVisible()
  await page.getByRole("button", { name: "5000m", exact: true }).click()
  await page.getByRole("textbox", { name: "최고기록" }).fill("21:40")
  await page.getByRole("checkbox", { name: /친구가 이 기록/u }).check()
  await page.getByRole("button", { name: "친구의 러닝 풀이 보기" }).click()
  await expect(page.getByRole("heading", { name: "5000m에 담긴 친구의 리듬" })).toBeVisible()
  await page.getByRole("button", { name: "내 기록과 러닝 궁합 보기" }).click()
  await expect(page.getByRole("group", { name: "내 종목" })).toBeVisible()
  await page.getByRole("button", { name: "5000m", exact: true }).click()
  await page.getByRole("textbox", { name: "최고기록" }).fill("20:30")
  await page.getByRole("button", { name: "친구 기록과 비교하기" }).click()
  await expect(page.locator(".record-reading__pair > div").filter({ hasText: "나 · 5000m" })).toContainText("20분 30초")
  await expect(page.locator(".record-reading__pair > div").filter({ hasText: "친구 · 5000m" })).toContainText("21분 40초")
  await page.getByRole("button", { name: "풀이 닫기" }).click()
  await page.goBack()
  await page.goForward()
  await expect(page.getByRole("group", { name: "풀이 내용" })).toHaveCount(0)
  await expect(page.getByRole("heading", { name: "더보기", exact: true })).toBeVisible()
})
