import { expect, test } from "@playwright/test"

test.use({ serviceWorkers: "block" })
for (const width of [320, 375, 1440]) {
  test(`profile minimal and extended journeys preserve answers at ${width}px`, async ({ page }, info) => {
    const errors: string[] = []; page.on("pageerror", error => errors.push(error.message))
    await page.setViewportSize({ width, height: width === 1440 ? 900 : 812 })
    await page.goto("/?app=1")
    await page.getByRole("navigation", { name: "주 탭" }).getByRole("button", { name: "오라클", exact: true }).click()
    await page.getByRole("button", { name: "러닝 취향" }).click()
    await page.getByRole("button", { name: "3문항으로 시작" }).click()
    await page.getByRole("button", { name: "건강과 체력", exact: true }).click()
    await page.getByRole("button", { name: "기분 전환", exact: true }).click()
    await page.getByRole("button", { name: "다음", exact: true }).click()
    await page.getByRole("button", { name: "대화할 수 있는 강도", exact: true }).click()
    await page.getByRole("button", { name: "혼자", exact: true }).click()
    await expect(page.locator(".running-profile h1")).toContainText("건강과 체력 · 기분 전환")
    await expect(page.locator("html")).toHaveJSProperty("scrollWidth", width)
    await page.screenshot({ path: info.outputPath(`profile-${width}.png`) })
    await page.goBack()
    await expect(page.getByRole("button", { name: "혼자", exact: true })).toHaveAttribute("aria-pressed", "true")
    await page.goForward()
    await page.getByRole("button", { name: /대회·종목·운동 취향 더하기/ }).click()
    await page.getByRole("button", { name: "그날 상황에 맞춰", exact: true }).click()
    await page.getByRole("button", { name: "내 기록 경신", exact: true }).click()
    await page.getByRole("button", { name: "대회 분위기와 경험", exact: true }).click()
    await page.getByRole("button", { name: "다음", exact: true }).click()
    await page.getByRole("button", { name: "800m", exact: true }).click()
    await page.getByRole("button", { name: "마라톤", exact: true }).click()
    await page.getByRole("button", { name: "다음", exact: true }).click()
    await page.getByRole("button", { name: "지금은 건너뛰기" }).click()
    await page.getByRole("button", { name: "경험이 없어 아직 몰라요" }).click()
    await page.getByRole("button", { name: "다음", exact: true }).click()
    await page.getByRole("button", { name: "시간이 부족해요" }).click()
    await page.getByRole("button", { name: "프로필 보기", exact: true }).click()
    await expect(page.locator(".running-profile__facts")).toContainText("800m · 마라톤")
    for (const tab of ["경기 기록", "최근 훈련", "변화", "취향"]) {
      await page.getByRole("navigation", { name: "러닝 취향 항목" }).getByRole("button", { name: tab, exact: true }).click()
    }
    await expect(page.locator(".running-profile__facts")).toContainText("800m · 마라톤")
    expect(await page.evaluate(() => JSON.stringify(history.state))).not.toMatch(/health|motives|answers|marathon/)
    await page.getByRole("button", { name: "프로필 닫기" }).click()
    await expect(page.locator(".running-profile")).toHaveCount(0)
    await page.goBack(); await page.goForward()
    await expect(page.locator(".running-profile__facts")).toHaveCount(0)
    expect(errors).toEqual([])
  })
}

test("profile enlarged text, reduced motion and draft cancellation", async ({ page }, info) => {
  await page.setViewportSize({ width: 320, height: 812 })
  await page.emulateMedia({ reducedMotion: "reduce" })
  await page.goto("/?app=1")
  await page.getByRole("navigation", { name: "주 탭" }).getByRole("button", { name: "오라클", exact: true }).click()
  await page.getByRole("button", { name: "러닝 취향" }).click()
  await page.getByRole("button", { name: "3문항으로 시작" }).click()
  await expect(page.locator(".running-profile__stage")).toHaveCSS("animation-name", "none")
  await page.getByRole("button", { name: "건강과 체력", exact: true }).click()
  page.once("dialog", dialog => dialog.dismiss())
  await page.getByRole("button", { name: "프로필 닫기" }).click()
  await expect(page.getByRole("button", { name: "건강과 체력", exact: true })).toHaveAttribute("aria-pressed", "true")
  await page.goBack()
  page.once("dialog", dialog => dialog.dismiss())
  await page.goBack()
  await expect(page.locator(".running-profile")).toBeVisible()
  await page.getByRole("button", { name: "내 응답 바꾸기" }).click()
  await expect(page.getByRole("button", { name: "건강과 체력", exact: true })).toHaveAttribute("aria-pressed", "true")
  await page.evaluate(() => {
    document.querySelectorAll<HTMLElement>(".running-profile h1,.running-profile p,.running-profile button,.running-profile__header,.running-profile .info-disclosure summary").forEach(element => {
      element.style.fontSize = `${parseFloat(getComputedStyle(element).fontSize) * 2}px`
    })
  })
  await expect(page.locator("html")).toHaveJSProperty("scrollWidth", 320)
  await page.screenshot({ path: info.outputPath("profile-text-200.png") })
  await page.getByRole("button", { name: "다음", exact: true }).focus()
  await page.keyboard.press("Enter")
  await expect(page.getByRole("heading", { name: "어떤 강도로 달리는 게 좋나요?" })).toBeFocused()
})
