import { expect, test } from "@playwright/test"

test.use({ serviceWorkers: "block" })
test.beforeEach(async ({ page, baseURL }) => {
  const origin = new URL(baseURL!).origin
  await page.route("**/*", route => new URL(route.request().url()).origin === origin ? route.continue() : route.abort())
  await page.goto("/?app=1&uitest=1")
  await page.evaluate(() => { localStorage.clear(); sessionStorage.clear() })
  await page.reload()
})

test("analysis has a clear reading start and meaningful choices on a narrow phone", async ({ page }, info) => {
  await page.setViewportSize({ width: 375, height: 812 })
  await page.getByRole("navigation", { name: "주 탭" }).getByRole("button", { name: "오라클", exact: true }).click()
  const title = page.getByRole("heading", { name: "내 훈련 살펴보기", exact: true })
  await expect(title).toBeVisible()
  await expect(title).toHaveCSS("font-size", "24px")
  const image = page.locator('.trends-hub__guide img')
  await expect.poll(() => image.evaluate(node => (node as HTMLImageElement).naturalWidth)).toBe(256)
  await page.getByText("훈련량·구성·변화 보기", { exact: true }).click()
  const choice = page.getByRole("group", { name: "훈련 분석 자세히 보기" }).getByRole("button", { name: "훈련량", exact: true })
  await expect(choice).toHaveAccessibleDescription("달린 거리 합계")
  expect((await choice.boundingBox())!.height).toBeGreaterThanOrEqual(44)
  expect(await page.locator('.app-scroll-region').evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true)
  await page.screenshot({ path: info.outputPath("analysis-375.png"), fullPage: true })
  await choice.click()
  await expect(page.getByRole("heading", { name: "훈련량 보기", exact: true })).toBeVisible()
  await expect(page.getByRole("region", { name: "누적 거리와 변화" })).toBeVisible()
})

test("pace title and event actions fit at 320px and input keeps its original value on Back", async ({ page }, info) => {
  await page.setViewportSize({ width: 320, height: 740 })
  await page.getByRole("button", { name: "더보기", exact: true }).click()
  await page.getByRole("button", { name: "페이스 계산", exact: true }).click()
  const title = page.getByRole("heading", { name: "어떤 종목의 기록인가요?", exact: true })
  await expect(title).toBeFocused()
  await expect(title).toHaveCSS("font-size", "24px")
  await expect(page.getByText("기록으로 거리별 평균 시간을 계산해요.")).toBeVisible()
  const image = page.locator('.pace-tool .task-guide img')
  await expect.poll(() => image.evaluate(node => (node as HTMLImageElement).naturalWidth)).toBe(256)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: info.outputPath("pace-320.png"), fullPage: true })
  await page.getByRole("button", { name: "800m", exact: true }).click()
  await expect(image).toHaveCount(0)
  await page.getByRole("textbox", { name: "분", exact: true }).fill("2")
  await page.getByRole("textbox", { name: "초", exact: true }).fill("1.5")
  await page.getByRole("button", { name: "페이스 보기", exact: true }).click()
  await expect(page.getByText("0:30.4", { exact: true })).toBeVisible()
  await page.goBack()
  await expect(page.getByRole("textbox", { name: "초", exact: true })).toHaveValue("1.5")
})

test("record result retains its numbers and actions when artwork fails and text is enlarged", async ({ page }, info) => {
  await page.setViewportSize({ width: 320, height: 740 })
  await page.emulateMedia({ reducedMotion: "reduce" })
  await page.route("**/record-stopwatch-v3.webp", route => route.abort())
  await page.getByRole("button", { name: "더보기", exact: true }).click()
  await page.getByRole("button", { name: "최고기록으로 풀이하기", exact: true }).click()
  await expect(page.getByRole("heading", { name: "어떤 기록을 살펴볼까요?" })).toBeFocused()
  await page.getByRole("button", { name: "5000m", exact: true }).click()
  await page.getByRole("textbox", { name: "최고기록" }).fill("20:30")
  await page.getByRole("button", { name: "나의 러닝 풀이 보기", exact: true }).click()
  await expect(page.getByRole("heading", { name: "내 5000m 기록 요약" })).toBeFocused()
  await expect(page.locator('.record-reading__signature img')).toHaveCount(0)
  expect((await page.locator('.record-reading__signature > div').boundingBox())!.width).toBeGreaterThan(200)
  await expect(page.getByText("4분 6초", { exact: true })).toBeVisible()
  await expect(page.getByText("최고기록을 나눈 값이며, 오늘의 훈련 목표는 아니에요.")).toBeVisible()
  await page.evaluate(() => {
    const elements = [...document.querySelectorAll<HTMLElement>('.record-reading h1, .record-reading p, .record-reading button, .record-reading strong, .record-reading small, .record-reading span, .record-reading dt, .record-reading dd')]
      .map(element => ({ element, size: parseFloat(getComputedStyle(element).fontSize) }))
    for (const { element, size } of elements) element.style.fontSize = `${size * 2}px`
  })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: info.outputPath("record-large-text-320.png"), fullPage: true })
  await page.getByRole("group", { name: "풀이 내용" }).getByRole("button", { name: "400m 평균", exact: true }).click()
  await expect(page.getByRole("heading", { name: "400m 평균 시간" })).toBeFocused()
})
