import { expect, test } from "@playwright/test"

test.use({ serviceWorkers: "block" })
test.beforeEach(async ({ page, baseURL }) => {
  const origin = new URL(baseURL!).origin
  await page.route("**/*", route => new URL(route.request().url()).origin === origin ? route.continue() : route.abort())
  await page.goto("/?app=1&uitest=1")
  await page.evaluate(() => { localStorage.clear(); sessionStorage.clear() })
  await page.reload()
})

test("one question, retained answers, native Back and a single Quick completion", async ({ page }, info) => {
  await page.setViewportSize({ width: 375, height: 667 })
  await page.getByRole("button", { name: "오늘 기록 남기기", exact: true }).click()
  await expect(page.getByRole("navigation", { name: "주 탭" })).toHaveCount(0)
  await expect(page.getByRole("button", { name: "오전", exact: true })).toHaveCount(0)
  await page.getByRole("button", { name: "운동을 마쳤어요", exact: true }).click()
  await page.getByRole("button", { name: "오후", exact: true }).click()
  await expect(page.getByRole("heading", { name: "몸에는 어느 정도로 느껴졌나요?" })).toBeFocused()
  await page.goBack()
  await expect(page.getByRole("heading", { name: "언제 했나요?" })).toBeFocused()
  await expect(page.getByRole("button", { name: "오후", exact: true })).toHaveAttribute("aria-pressed", "true")
  await page.getByRole("button", { name: "오후", exact: true }).click()
  await page.getByRole("button", { name: /힘든 정도 6\/10,/ }).click()
  await page.getByRole("button", { name: "없어요", exact: true }).click()
  await expect(page.getByRole("heading", { name: "이 내용으로 남길까요?" })).toBeFocused()
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem("trainoracle.journal.v1") ?? "[]"))).toHaveLength(0)
  await page.screenshot({ path: info.outputPath("quick-review-375.png"), fullPage: true })
  await page.getByRole("button", { name: "이대로 저장", exact: true }).click()
  await expect(page.getByRole("heading", { name: "오늘 기록을 남겼어요." })).toBeVisible()
  await expect(page.locator(".journal-save-result")).toBeVisible()
  await expect(page.locator(".saved-toast")).toHaveCount(0)
  await expect(page.locator(".journal-save-result")).toContainText("반영됐어요")
  await page.screenshot({ path: info.outputPath("quick-saved-unified-375.png"), fullPage: true })
  await page.getByRole("button", { name: "완료", exact: true }).click()
  await expect(page.locator(".journal-save-result")).toHaveCount(0)
  await expect(page.getByRole("navigation", { name: "주 탭" })).toBeVisible()
  const stored = await page.evaluate(() => JSON.parse(localStorage.getItem("trainoracle.journal.v1") ?? "[]"))
  expect(stored).toHaveLength(1)
  expect(stored[0]).toMatchObject({ activityOutcome: "COMPLETED", activitySlot: "PM", rpe: 6 })
})

test("large text and narrow screens keep the current choices operable", async ({ page }, info) => {
  await page.setViewportSize({ width: 320, height: 740 })
  await page.emulateMedia({ reducedMotion: "reduce" })
  await page.getByRole("button", { name: "오늘 기록 남기기", exact: true }).click()
  await page.evaluate(() => {
    const sizes = [...document.querySelectorAll<HTMLElement>(".task-flow *")]
      .map(element => ({ element, size: parseFloat(getComputedStyle(element).fontSize) }))
    for (const { element, size } of sizes) element.style.fontSize = `${size * 2}px`
  })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  const rest = page.getByRole("button", { name: "오늘은 쉬었어요", exact: true })
  await rest.scrollIntoViewIfNeeded()
  expect((await rest.boundingBox())!.height).toBeGreaterThanOrEqual(44)
  await page.screenshot({ path: info.outputPath("quick-large-text-320.png"), fullPage: true })
  await rest.click()
  await expect(page.getByRole("heading", { name: "이 내용으로 남길까요?" })).toBeVisible()
  await expect(page.getByRole("button", { name: /힘든 정도 6\/10,/ })).toHaveCount(0)
})

test("plan native Back returns one question and preserves unsent record input", async ({ page }, info) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.getByRole("button", { name: "훈련 계획 만들기", exact: true }).click()
  expect((await page.locator(".app-shell").boundingBox())!.width).toBeGreaterThan(520)
  await page.getByRole("button", { name: "1500m", exact: true }).click()
  await page.getByRole("button", { name: "내 기록", exact: true }).click()
  await page.getByLabel("분", { exact: true }).fill("4")
  await page.getByLabel("초", { exact: true }).fill("23.4")
  await page.goBack()
  await expect(page.getByRole("heading", { name: "1500m 기록이 있나요?" })).toBeFocused()
  await page.getByRole("button", { name: "내 기록", exact: true }).click()
  await expect(page.getByLabel("초", { exact: true })).toHaveValue("23.4")
  await page.getByRole("button", { name: "기록 입력 완료", exact: true }).click()
  await page.getByRole("button", { name: /빠른 훈련과 쉬운 훈련을 나눠 꾸준히 해왔어요/ }).click()
  await expect(page.getByRole("heading", { name: "이번 9일 중 며칠 훈련할까요?" })).toBeFocused()
  await page.goBack()
  await expect(page.getByRole("button", { name: /빠른 훈련과 쉬운 훈련을 나눠 꾸준히 해왔어요/ })).toHaveAttribute("aria-pressed", "true")
  await expect(page.getByRole("group", { name: "앞서 선택한 답 수정" })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: info.outputPath("plan-return-desktop.png"), fullPage: true })
})

for (const kind of ["post-session", "evening", "race"] as const) {
  test(`${kind} edits one answer and saves through a single persistent result`, async ({ page }, info) => {
    await page.setViewportSize({ width: 375, height: 812 })
    await page.getByRole("button", { name: "기록하기", exact: true }).click()
    await page.getByTestId(`entry-choice-${kind}`).click()
    await expect(page.getByRole("navigation", { name: "주 탭" })).toHaveCount(0)
    await page.getByRole("button", { name: "지금 입력 확인", exact: true }).click()
    if (kind === "post-session") {
      await page.getByRole("button", { name: "실제로 한 운동 수정", exact: true }).click()
      await page.getByLabel("세션 제목", { exact: true }).fill("합성 운동 기록")
      await page.getByRole("button", { name: "입력 확인으로", exact: true }).click()
      await expect(page.getByRole("heading", { name: "입력 확인", exact: true })).toBeFocused()
      await expect(page.getByText("합성 운동 기록", { exact: false })).toBeVisible()
    } else if (kind === "evening") {
      await page.getByRole("button", { name: /^체중 · 안정시 심박 입력$/ }).click()
      await page.getByLabel("체중 (kg)", { exact: true }).fill("60.5")
      await page.getByRole("button", { name: "입력 확인으로", exact: true }).click()
      await expect(page.getByRole("heading", { name: "입력 확인", exact: true })).toBeFocused()
      await expect(page.getByText(/60.5/)).toBeVisible()
    } else {
      await page.getByRole("button", { name: "경기 정보 수정", exact: true }).click()
      await page.getByRole("button", { name: "경기 직후", exact: true }).click()
      await page.getByRole("textbox", { name: "경기 기록", exact: true }).fill("16:42.18")
      await page.getByRole("button", { name: "지금 입력 확인", exact: true }).click()
      await expect(page.getByText(/16:42.18/)).toBeVisible()
    }
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: info.outputPath(`${kind}-review-375.png`), fullPage: true })
    await page.getByRole("button", { name: /^저장/ }).click()
    await expect(page.locator(".journal-save-result")).toBeVisible()
    await expect(page.getByRole("button", { name: "기록 보기", exact: true })).toBeVisible()
    await page.screenshot({ path: info.outputPath(`${kind}-saved-375.png`), fullPage: true })
    await page.getByRole("button", { name: "닫기", exact: true }).click()
    await expect(page.locator(".journal-save-result")).toHaveCount(0)
    await expect(page.getByRole("navigation", { name: "주 탭" })).toBeVisible()
    const records = await page.evaluate(() => JSON.parse(localStorage.getItem("trainoracle.journal.v1") ?? "[]"))
    expect(records).toHaveLength(1)
    expect(records[0].kind).toBe(kind)
  })
}
