import { act, cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react"
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest"
import { WorkoutMemoTool } from "./WorkoutMemoTool"
import { memoSessionFixture } from "../domain/workout-memo.test-fixtures"
import { downloadMemo, renderWorkoutMemoPng } from "../domain/workout-memo-export"
import { More } from "../screens/More"

const scope = vi.hoisted(() => ({ changed: () => {} }))
vi.mock("../domain/account/local-journal-ownership", async importOriginal => ({
  ...await importOriginal<typeof import("../domain/account/local-journal-ownership")>(),
  onLocalJournalScopeChange: (callback: () => void) => { scope.changed = callback; return () => {} },
}))
vi.mock("../domain/workout-memo-export", async importOriginal => ({ ...await importOriginal<typeof import("../domain/workout-memo-export")>(),
  renderWorkoutMemoPng: vi.fn(), downloadMemo: vi.fn() }))

beforeEach(() => {
  vi.mocked(renderWorkoutMemoPng).mockResolvedValue(new Blob(["synthetic-png"], { type: "image/png" }))
  Object.defineProperty(navigator, "clipboard", { configurable: true, value: { writeText: vi.fn().mockResolvedValue(undefined) } })
  Object.defineProperty(navigator, "canShare", { configurable: true, value: undefined })
  Object.defineProperty(navigator, "share", { configurable: true, value: undefined })
})
afterEach(() => { cleanup(); localStorage.clear(); vi.clearAllMocks() })
const open = () => fireEvent.click(screen.getByRole("button", { name: "자세히" }))
const openCustomization = () => fireEvent.click(screen.getByText("표현·꾸미기"))

describe("workout memo read-only actions", () => {
  it("does not create another modal or history entry and copies the current snapshot", async () => {
    const history = vi.spyOn(window.history, "pushState")
    render(<WorkoutMemoTool session={memoSessionFixture()} date="2026-09-20" state="PLAN" />)
    open()
    fireEvent.click(screen.getByRole("button", { name: "복사" }))
    await waitFor(() => expect(screen.getByRole("status")).toHaveTextContent("복사했어요."))
    expect(navigator.clipboard.writeText).toHaveBeenCalledWith(expect.stringContaining("2026.09.20 (일) · 오후"))
    expect(history).not.toHaveBeenCalled()
    expect(screen.queryByRole("dialog")).toBeNull()
  })
  it("updates colour using swatches and downloads one PNG despite a double click", async () => {
    render(<WorkoutMemoTool session={memoSessionFixture()} />); open()
    openCustomization()
    fireEvent.click(screen.getByRole("button", { name: "분홍 종이" }))
    const button = screen.getByRole("button", { name: "저장" })
    fireEvent.click(button); fireEvent.click(button)
    await waitFor(() => expect(downloadMemo).toHaveBeenCalledTimes(1))
    expect(renderWorkoutMemoPng).toHaveBeenCalledWith(expect.anything(), "pink", "method")
    expect(screen.getByRole("button", { name: "분홍 종이" })).toHaveAttribute("aria-pressed", "true")
  })
  it("provides selectable text when clipboard is denied", async () => {
    vi.mocked(navigator.clipboard.writeText).mockRejectedValue(new DOMException("denied", "NotAllowedError"))
    render(<WorkoutMemoTool session={memoSessionFixture()} />); open()
    fireEvent.click(screen.getByRole("button", { name: "복사" }))
    expect((await screen.findByRole("textbox", { name: "복사할 훈련 메모" }) as HTMLTextAreaElement).value).toContain("TRAINORACLE")
    expect(screen.getByRole("alert")).toHaveTextContent("자동 복사가 막혔어요.")
  })
  it("uses a download fallback for sharing without claiming a remote share", async () => {
    render(<WorkoutMemoTool session={memoSessionFixture()} />); open()
    fireEvent.click(screen.getByRole("button", { name: "공유" }))
    await waitFor(() => expect(downloadMemo).toHaveBeenCalledTimes(1))
    expect(screen.getByRole("status")).toHaveTextContent("파일 공유 대신")
  })
  it("does not call a cancelled share an error", async () => {
    Object.defineProperty(navigator, "canShare", { configurable: true, value: () => true })
    Object.defineProperty(navigator, "share", { configurable: true, value: vi.fn().mockRejectedValue(new DOMException("cancelled", "AbortError")) })
    render(<WorkoutMemoTool session={memoSessionFixture()} />); open()
    fireEvent.click(screen.getByRole("button", { name: "공유" }))
    await waitFor(() => expect(navigator.share).toHaveBeenCalledOnce())
    expect(screen.queryByRole("alert")).toBeNull()
    expect(downloadMemo).not.toHaveBeenCalled()
  })
  it("discards an in-flight export when the prescription changes", async () => {
    let finish!: (blob: Blob) => void
    vi.mocked(renderWorkoutMemoPng).mockImplementationOnce(() => new Promise(resolve => { finish = resolve }))
    const session = memoSessionFixture()
    const view = render(<WorkoutMemoTool session={session} />); open()
    fireEvent.click(screen.getByRole("button", { name: "저장" }))
    view.rerender(<WorkoutMemoTool session={session} date="2026-09-22" />)
    finish(new Blob(["old-png"]))
    await waitFor(() => expect(screen.getByRole("button", { name: "저장" })).not.toBeDisabled())
    expect(downloadMemo).not.toHaveBeenCalled()
  })
  it("invalidates the old memo and pending download on account scope change", async () => {
    let finish!: (blob: Blob) => void
    vi.mocked(renderWorkoutMemoPng).mockImplementationOnce(() => new Promise(resolve => { finish = resolve }))
    render(<WorkoutMemoTool session={memoSessionFixture()} />); open()
    fireEvent.click(screen.getByRole("button", { name: "저장" }))
    act(() => scope.changed())
    finish(new Blob(["old-private-png"]))
    await waitFor(() => expect(screen.queryByText("훈련 메모")).toBeNull())
    expect(downloadMemo).not.toHaveBeenCalled()
  })
  it("reports renderer failure without claiming a download", async () => {
    vi.mocked(renderWorkoutMemoPng).mockRejectedValueOnce(new Error("canvas failed"))
    render(<WorkoutMemoTool session={memoSessionFixture()} />); open()
    fireEvent.click(screen.getByRole("button", { name: "저장" }))
    expect(await screen.findByRole("alert")).toHaveTextContent("내보내지 못했어요")
    expect(downloadMemo).not.toHaveBeenCalled()
  })
  it("opens the existing pace calculator from More", () => {
    const onOpenPaceCalculator = vi.fn()
    render(<More onBack={vi.fn()} onOpenMinji={vi.fn()} onOpenGuide={vi.fn()} onOpenPaceCalculator={onOpenPaceCalculator} />)
    fireEvent.click(screen.getByRole("button", { name: "페이스 계산" }))
    expect(onOpenPaceCalculator).toHaveBeenCalledOnce()
  })
  it("switches between full and compact without hiding recovery, preparation or safety", async () => {
    render(<WorkoutMemoTool session={memoSessionFixture()} />); open()
    const preview = screen.getByRole("article", { name: "훈련 메모 미리보기" })
    fireEvent.click(screen.getByRole("button", { name: "간단히" }))
    expect(preview).toHaveAttribute("data-layout", "compact")
    expect(preview).toHaveAttribute("data-view", "standard")
    expect(preview).toHaveTextContent("반복 사이")
    expect(preview).toHaveTextContent("가속 달리기 (전력질주 아님)")
    expect(preview).toHaveTextContent("새 통증이나 심해지는 통증이 생기면 중단")
    fireEvent.click(screen.getByRole("button", { name: "저장" }))
    await waitFor(() => expect(renderWorkoutMemoPng).toHaveBeenCalledWith(expect.anything(), "yellow", "standard"))
    fireEvent.click(screen.getByRole("button", { name: "자세히" }))
    expect(preview).toHaveAttribute("data-layout", "full")
  })
  it("does not reuse a full-layout image after choosing compact", async () => {
    render(<WorkoutMemoTool session={memoSessionFixture()} />); open()
    fireEvent.click(screen.getByRole("button", { name: "저장" }))
    await waitFor(() => expect(downloadMemo).toHaveBeenCalledTimes(1))
    fireEvent.click(screen.getByRole("button", { name: "간단히" }))
    fireEvent.click(screen.getByRole("button", { name: "저장" }))
    await waitFor(() => expect(downloadMemo).toHaveBeenCalledTimes(2))
    expect(renderWorkoutMemoPng).toHaveBeenCalledTimes(2)
    expect(vi.mocked(renderWorkoutMemoPng).mock.calls.map(call => call[2])).toEqual(["method", "standard"])
  })
  it("shows both choices immediately and opens the chosen memo in one click", () => {
    render(<WorkoutMemoTool session={memoSessionFixture()} />)
    expect(screen.getByRole("button", { name: "간단히" })).toBeVisible()
    expect(screen.getByRole("button", { name: "자세히" })).toBeVisible()
    expect(screen.queryByRole("article", { name: "훈련 메모 미리보기" })).toBeNull()
    fireEvent.click(screen.getByRole("button", { name: "간단히" }))
    const preview = screen.getByRole("article", { name: "훈련 메모 미리보기" })
    const customization = screen.getByText("표현·꾸미기").closest("details")
    const actions = screen.getByRole("group", { name: "메모 가져가기" })
    expect(preview).toHaveAttribute("data-layout", "compact")
    expect(customization).not.toHaveAttribute("open")
    expect(preview.compareDocumentPosition(customization!) & Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy()
    expect(customization!.compareDocumentPosition(actions) & Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy()
    expect(screen.getByRole("button", { name: "간단히" })).toHaveAttribute("aria-expanded", "true")
    fireEvent.click(screen.getByRole("button", { name: "메모 접기" }))
    expect(screen.queryByRole("article", { name: "훈련 메모 미리보기" })).toBeNull()
    expect(screen.getByRole("button", { name: "자세히" })).toBeVisible()
    fireEvent.click(screen.getByRole("button", { name: "자세히" }))
    expect(screen.getByRole("article", { name: "훈련 메모 미리보기" })).toHaveAttribute("data-layout", "full")
  })
  it("cancels a pending download when the memo is collapsed and allows direct reopening", async () => {
    let finish!: (blob: Blob) => void
    vi.mocked(renderWorkoutMemoPng).mockImplementationOnce(() => new Promise(resolve => { finish = resolve }))
    render(<WorkoutMemoTool session={memoSessionFixture()} />); open()
    fireEvent.click(screen.getByRole("button", { name: "저장" }))
    fireEvent.click(screen.getByRole("button", { name: "메모 접기" }))
    await act(async () => finish(new Blob(["cancelled-png"])))
    expect(downloadMemo).not.toHaveBeenCalled()
    fireEvent.click(screen.getByRole("button", { name: "간단히" }))
    expect(screen.getByRole("button", { name: "저장" })).not.toBeDisabled()
    expect(screen.queryByRole("status")).toBeNull()
  })
  it("separates depth from wording and remembers each group's view without applying a plan", () => {
    const session = memoSessionFixture(), before = JSON.stringify(session)
    render(<WorkoutMemoTool session={session} />)
    fireEvent.click(screen.getByRole("button", { name: "간단히" }))
    openCustomization()
    fireEvent.click(screen.getByRole("button", { name: "핵심만" }))
    fireEvent.click(screen.getByRole("button", { name: "훈련 표기" }))
    const preview = screen.getByRole("article", { name: "훈련 메모 미리보기" })
    expect(preview).toHaveAttribute("data-view", "core")
    expect(session.prescription.kind === "PACE_TARGET" && session.prescription.repetitionRecoverySeconds).toBe(150)
    expect(preview).toHaveTextContent("150s Jog")
    expect(preview).toHaveTextContent("RPE 2–3")
    fireEvent.click(screen.getByRole("button", { name: "자세히" }))
    fireEvent.click(screen.getByRole("button", { name: "설명까지" }))
    expect(screen.getByRole("region", { name: "훈련 설명" })).toHaveTextContent("공통")
    fireEvent.click(screen.getByRole("button", { name: "간단히" }))
    expect(preview).toHaveAttribute("data-view", "core")
    fireEvent.click(screen.getByRole("button", { name: "자세히" }))
    expect(preview).toHaveAttribute("data-view", "explained")
    fireEvent.click(screen.getByRole("button", { name: "쉬운 말" }))
    expect(preview).toHaveTextContent("150초 조깅")
    expect(preview).toHaveTextContent("힘든 정도 2–3/10")
    expect(JSON.stringify(session)).toBe(before)
  })
  it("exports the selected wording and detail, and does not reuse the previous wording's image", async () => {
    render(<WorkoutMemoTool session={memoSessionFixture()} state="HISTORICAL" />); open(); openCustomization()
    fireEvent.click(screen.getByRole("button", { name: "저장" }))
    await waitFor(() => expect(downloadMemo).toHaveBeenCalledTimes(1))
    fireEvent.click(screen.getByRole("button", { name: "훈련 표기" }))
    fireEvent.click(screen.getByRole("button", { name: "저장" }))
    await waitFor(() => expect(downloadMemo).toHaveBeenCalledTimes(2))
    expect(vi.mocked(renderWorkoutMemoPng).mock.calls.map(call => call[0].wording)).toEqual(["PLAIN", "COACH"])
    fireEvent.click(screen.getByRole("button", { name: "설명까지" }))
    fireEvent.click(screen.getByRole("button", { name: "복사" }))
    await waitFor(() => expect(navigator.clipboard.writeText).toHaveBeenCalledWith(expect.stringContaining("당시 선택 이유를 복원한 것은 아니에요")))
    expect(navigator.clipboard.writeText).toHaveBeenCalledWith(expect.stringContaining("설명 버전:"))
  })
})
