export {
  AVATAR_DECORATION_IDS,
  DECORATION_CATALOG,
  DECORATION_IDS,
  DECORATION_SLOTS,
  EMOJI_STICKER_GROUPS,
  EMOJI_STICKER_IDS,
  EMOJI_STICKER_SLOTS,
  INK_DECORATION_IDS,
  PAID_DECORATION_IDS,
  PLACEMENT_DECORATION_IDS,
  STAMP_DECORATION_IDS,
  STARTER_DECORATION_IDS,
  STICKER_DECORATION_IDS,
  TAPE_DECORATION_IDS,
  TEXT_INK_DEFINITIONS,
  TEXT_INK_IDS,
  TEXT_STICKER_ITEM_ID,
  TEXT_STICKER_MAX_LENGTH,
  THEME_DECORATION_IDS,
  decorationCatalogItem,
  isAvatarDecorationId,
  isDecorationId,
  isDecorationSlot,
  isEmojiStickerId,
  isEmojiStickerSlot,
  isInkDecorationId,
  isPaidDecorationId,
  isPlacementDecorationId,
  isTextInkId,
  isThemeDecorationId,
  textInkColor,
} from "./decoration-catalog"
export type {
  AvatarDecorationId,
  DecorationCatalogItem,
  DecorationId,
  DecorationSlot,
  EmojiStickerGroupId,
  EmojiStickerId,
  EmojiStickerSlot,
  InkDecorationId,
  PaidDecorationId,
  PlacementDecorationId,
  StampDecorationId,
  StickerDecorationId,
  TapeDecorationId,
  TextInkId,
  ThemeDecorationId,
} from "./decoration-catalog"
export {
  MAX_DECORATION_ITEMS_PER_PAGE,
  V2_SLOT_DEFAULT_TRANSFORMS,
  createEmptyDecorationState,
  decorationPlacementTransformSchema,
  decorationStateSchema,
  isCompatiblePlacement,
  isTextStickerPageItem,
  migrateLegacyDecorationState,
  parseStoredDecorationState,
  parseStoredDecorationStateV2,
  parseStoredDecorationStateV3,
  textStickerTextSchema,
} from "./decoration-schema"
export type {
  DecorationPage,
  DecorationPageItem,
  DecorationPlacementTransform,
  DecorationState,
  DecorationTextPageItem,
} from "./decoration-schema"
export {
  DECORATION_STORAGE_KEY_V1,
  DECORATION_STORAGE_KEY_V2,
  DECORATION_STORAGE_KEY_V2_BACKUP,
  DECORATION_STORAGE_KEY_V3,
  activeDecorationStorageKeyV1,
  activeDecorationStorageKeyV2,
  activeDecorationStorageKeyV2Backup,
  activeDecorationStorageKeyV3,
  decorationItemOwned,
  loadDecorationState,
  readDecorationStateSerialized,
  purchaseDecoration,
  rememberDecorationUse,
  saveDecorationState,
  saveDecorationStateIfCurrent,
  toggleFavoriteDecoration,
} from "./decoration-store"
export type {
  DecorationPurchase,
  DecorationSaveFailureCode,
  DecorationSaveResult,
} from "./decoration-store"
