export type OracleTopicKind = "PERSONAL" | "COMPARISON" | "EDUCATION"
export type OracleDestination = "PROFILE" | "RECORDS" | "JOURNAL" | "CALENDAR" | "METHODS" | "PLAN_REVIEW" | "FRIENDS" | "SHARE_PREVIEW" | "GLOSSARY" | "EVIDENCE" | "QUIZ" | "EXAMPLE"
export type OracleEvidence = "ANSWERS" | "ANSWER_HISTORY" | "RACE_RECORDS" | "LAPS" | "GOAL" | "DEVICE_SOURCE" | "TRAINING" | "PLAN_SNAPSHOT" | "CONDITIONS" | "FRIEND_CONSENT" | "SHARE_CONSENT" | "REVIEWED_SOURCE"
type Row = readonly [id: string, title: string, kind: OracleTopicKind, evidence: readonly OracleEvidence[], destination: OracleDestination, explanation: string, limitation: string]

// Editorial catalog only. A topic entry is not a completed personalized analysis.
const rows: readonly Row[] = [
  ["A01", "내가 달리는 이유", "PERSONAL", ["ANSWERS"], "PROFILE", "기록 도전과 기분 전환처럼 여러 이유를 함께 볼 수 있어요.", "고른 동기를 성격 전체로 해석하지 않아요."],
  ["A02", "좋아하는 달리기 강도", "PERSONAL", ["ANSWERS"], "PROFILE", "좋아하는 강도와 실제로 수행한 강도는 나눠서 살펴봐요.", "강한 운동 선호는 체력이나 통증 인내 점수가 아니에요."],
  ["A03", "계획이 편한 순간", "PERSONAL", ["ANSWERS", "CONDITIONS"], "CALENDAR", "계획을 좋아하는 정도와 실제로 가능한 일정을 함께 살펴봐요.", "일정을 지키지 못한 이유를 의지 부족으로 판단하지 않아요."],
  ["A04", "이어 달릴까, 나눠 달릴까", "PERSONAL", ["ANSWERS"], "METHODS", "이어 달리기와 쉬었다 반복하기 중 어떤 방식이 좋은지 직접 고를 수 있어요.", "강도 선호만으로 좋아하는 운동 형태를 추측하지 않아요."],
  ["A05", "혼자와 함께", "PERSONAL", ["ANSWERS"], "FRIENDS", "혼자가 편한 날과 함께 달리고 싶은 날을 구분해 볼 수 있어요.", "혼자 달리기 선호는 사회성 평가가 아니에요."],
  ["A06", "한 가지로 정하지 않아도", "PERSONAL", ["ANSWERS"], "PROFILE", "중간 응답, 서로 다른 응답, 아직 모르는 응답은 각각 다르게 읽어요.", "답이 없다고 중간 점수나 혼합 유형을 만들지 않아요."],
  ["A07", "달리는 이유의 변화", "COMPARISON", ["ANSWER_HISTORY", "CONDITIONS"], "PROFILE", "서로 다른 시점에 직접 답한 이유를 나란히 볼 수 있어요.", "팀이나 학업이 변화의 원인이라고 자동으로 단정하지 않아요."],
  ["A08", "익숙함과 새로운 경험", "PERSONAL", ["ANSWERS"], "METHODS", "익숙한 방식의 즐거움과 새로운 경험에 대한 관심을 살펴봐요.", "새로운 것을 좋아한다고 더 높은 등급을 주지 않아요."],
  ["B01", "내 기록을 구간 초로", "PERSONAL", ["RACE_RECORDS"], "RECORDS", "실제 경기 평균 속도를 200m, 400m, 1km 단위로 읽을 수 있어요.", "평균 속도 환산은 새로운 반복 훈련 처방이 아니에요."],
  ["B02", "최근 경기와 최고기록", "COMPARISON", ["RACE_RECORDS"], "RECORDS", "최근 경기, 최근 12개월 최고, 입력된 최고기록을 구분해요.", "최근 기록이 느려진 원인은 기록만으로 알 수 없어요."],
  ["B03", "종목별 기록 나란히", "COMPARISON", ["RACE_RECORDS"], "RECORDS", "각 종목의 실제 기록을 나란히 읽고 예상값은 따로 표시해요.", "기록이 없는 종목의 재능이나 경험을 판단하지 않아요."],
  ["B04", "출발부터 마지막 구간까지", "PERSONAL", ["LAPS"], "RECORDS", "남아 있는 구간 기록으로 초반과 후반의 차이를 확인해요.", "없는 구간이나 마지막 스퍼트를 만들어 채우지 않아요."],
  ["B05", "경기 하나로 알 수 있는 것", "PERSONAL", ["RACE_RECORDS"], "RECORDS", "한 경기에서도 거리, 평균 속도, 달성 날짜를 확인할 수 있어요.", "경기 하나로 CS, ASR, 타고난 재능을 확정하지 않아요."],
  ["B06", "현재 기록과 목표의 간격", "COMPARISON", ["RACE_RECORDS", "GOAL"], "PLAN_REVIEW", "현재 기록과 목표기록에 해당하는 구간 초를 구분해요.", "목표기록은 현재 실력이 아니며 계획 변경에는 확인이 필요해요."],
  ["B07", "워치 예상과 실제 경기", "COMPARISON", ["DEVICE_SOURCE", "RACE_RECORDS"], "EVIDENCE", "기기 예상값과 실제 기록의 출처와 날짜를 함께 확인해요.", "두 값의 차이만으로 개인 보정 공식을 만들지 않아요."],
  ["C01", "좋아하는 훈련과 실제 훈련", "COMPARISON", ["ANSWERS", "TRAINING"], "JOURNAL", "직접 고른 운동 형태와 실제로 남긴 형태를 비교해요.", "취향과 실천의 차이를 의지나 회복 능력으로 해석하지 않아요."],
  ["C02", "훈련 목적이 쌓이는 모습", "PERSONAL", ["TRAINING"], "JOURNAL", "확인된 목적별 횟수와 분류하지 못한 기록을 함께 읽어요.", "훈련 횟수 비율은 실제 에너지 공급 비율이 아니에요."],
  ["C03", "내가 기록한 요일", "PERSONAL", ["TRAINING"], "CALENDAR", "기록된 운동 날짜를 달력에서 확인해요.", "기록이 없는 날을 휴식한 날이라고 확정하지 않아요."],
  ["C04", "오전과 오후의 다른 훈련", "PERSONAL", ["TRAINING"], "CALENDAR", "같은 날짜의 훈련도 세션별로 나눠 볼 수 있어요.", "중복 수신을 하루 두 번 훈련으로 세지 않아요."],
  ["C05", "보조 운동과 나의 여건", "PERSONAL", ["ANSWERS", "CONDITIONS"], "PROFILE", "보조 운동의 경험과 관심, 가능한 시간과 시설을 구분해요.", "기록이 없다는 이유로 운동하지 않는 원인을 추측하지 않아요."],
  ["C06", "달리기 외에 남긴 운동", "PERSONAL", ["TRAINING"], "JOURNAL", "웨이트, 점프, 자전거를 각 운동의 기록 단위로 읽어요.", "서로 다른 운동의 반복 수나 시간을 임의의 부하 점수로 합치지 않아요."],
  ["C07", "계획과 실제 수행", "COMPARISON", ["PLAN_SNAPSHOT", "TRAINING"], "PLAN_REVIEW", "당시 처방과 실제 남긴 수치를 나란히 확인해요.", "완료 체크만으로 모든 반복과 회복을 지켰다고 판단하지 않아요."],
  ["D01", "마음에 드는 훈련과 필요한 조건", "PERSONAL", ["ANSWERS", "GOAL", "REVIEWED_SOURCE"], "METHODS", "마음에 드는 점과 훈련 목적에 필요한 조건을 나눠 살펴봐요.", "취향이 맞는다는 이유만으로 처방이 허용되지는 않아요."],
  ["D02", "운동과 회복의 순서", "EDUCATION", ["REVIEWED_SOURCE"], "METHODS", "계속 달리는 구성과 나누어 달리는 구성은 운동과 회복 순서가 달라요.", "두 구성이 같은 자극이나 효과를 낸다고 단정하지 않아요."],
  ["D03", "이만큼 쉬는 이유", "EDUCATION", ["REVIEWED_SOURCE"], "METHODS", "회복의 길이와 방식은 해당 본운동 구성과 함께 읽어야 해요.", "모든 반복 훈련에 같은 회복 설명을 붙이지 않아요."],
  ["D04", "언덕에서는 무엇이 달라질까", "EDUCATION", ["REVIEWED_SOURCE"], "METHODS", "언덕 훈련은 경사와 운동, 회복 조건을 함께 확인해요.", "평지 경기 페이스를 언덕에 그대로 적용하지 않아요."],
  ["D05", "짧게 달리는 구간의 목적", "EDUCATION", ["REVIEWED_SOURCE"], "METHODS", "짧은 운동도 해당 훈련이 의도한 출력과 에너지 공급 특성으로 설명해요.", "모든 짧은 훈련을 가속 연습이나 기술 연습이라고 부르지 않아요."],
  ["D06", "시간과 장소에 맞는 조건", "PERSONAL", ["CONDITIONS", "REVIEWED_SOURCE"], "METHODS", "사용 가능한 시간, 장소, 장비를 방법의 요구 조건과 비교해요.", "시간이 맞는다고 안전과 효과가 검증되는 것은 아니에요."],
  ["D07", "웨이트와 점프의 다른 목적", "EDUCATION", ["REVIEWED_SOURCE"], "METHODS", "웨이트와 점프, 다른 보조 운동의 목적과 연구 조건을 구분해요.", "특정 연구 결과를 모든 러너에게 같은 기준으로 적용하지 않아요."],
  ["D08", "유명한 훈련법 읽기", "EDUCATION", ["REVIEWED_SOURCE"], "METHODS", "선수 사례를 읽을 때 구성뿐 아니라 그 선수의 조건도 확인해요.", "사례 소개는 그대로 따라 해도 된다는 허가가 아니에요."],
  ["E01", "친구와 기록 나란히", "COMPARISON", ["FRIEND_CONSENT", "RACE_RECORDS"], "FRIENDS", "허용된 같은 종목 기록과 달성 시점을 함께 읽어요.", "한 기록 차이를 전체 능력 순위로 바꾸지 않아요."],
  ["E02", "함께 달릴 수 있는 구간", "COMPARISON", ["FRIEND_CONSENT", "GOAL", "CONDITIONS"], "FRIENDS", "각자의 목적을 확인하고 준비, 본운동, 회복 중 함께할 부분을 찾아요.", "두 사람의 최고기록 평균으로 함께 달릴 페이스를 정하지 않아요."],
  ["E03", "같은 답과 다른 답", "COMPARISON", ["FRIEND_CONSENT", "ANSWERS"], "FRIENDS", "같은 버전의 질문에 답한 내용을 나란히 읽어요.", "둘 다 모른다는 답은 같은 취향으로 계산하지 않아요."],
  ["E04", "오늘의 목표가 다를 때", "COMPARISON", ["FRIEND_CONSENT", "GOAL"], "FRIENDS", "각자가 직접 정한 목표를 확인하고 함께할 부분을 의논해요.", "친구의 목표를 기록에서 추측하지 않아요."],
  ["E05", "같은 기간의 훈련 비교", "COMPARISON", ["FRIEND_CONSENT", "TRAINING"], "FRIENDS", "공유한 기간과 자료 범위가 같은지 먼저 확인해요.", "거리나 횟수 차이에 건강 점수를 붙이지 않아요."],
  ["E06", "공유 전에 확인하기", "EDUCATION", ["SHARE_CONSENT"], "SHARE_PREVIEW", "공유할 사실과 나만 볼 내용을 미리보기에서 구분해요.", "비교 동의가 외부 공개 동의를 대신하지 않아요."],
  ["F01", "이번 대회에서 중요한 것", "PERSONAL", ["GOAL"], "PROFILE", "기록, 완주, 경험처럼 이번 대회의 목표를 여러 개 고를 수 있어요.", "대회 목표를 한 가지 성격으로 고정하지 않아요."],
  ["F02", "출발 페이스와 경기 전개", "PERSONAL", ["LAPS", "GOAL", "CONDITIONS"], "RECORDS", "실제 초반 구간을 목표와 경기 조건과 함께 읽어요.", "빠른 출발을 충동적인 성격의 증거로 삼지 않아요."],
  ["F03", "처음 달리는 종목", "EDUCATION", ["REVIEWED_SOURCE"], "METHODS", "처음 도전하는 거리에서는 필요한 준비 항목부터 확인해요.", "기록이 없다는 것은 재능이 부족하다는 뜻이 아니에요."],
  ["F04", "최고기록 말고 남긴 것", "PERSONAL", ["GOAL", "RACE_RECORDS"], "JOURNAL", "직접 정한 목표와 경기에서 남긴 결과를 함께 읽어요.", "느린 기록만 보고 경험이나 추억이 목표였다고 해석하지 않아요."],
  ["F05", "다른 날, 다른 경기 조건", "COMPARISON", ["RACE_RECORDS", "CONDITIONS"], "RECORDS", "확인된 코스와 날씨, 운영 조건을 나란히 볼 수 있어요.", "조건을 알아도 기록 차이의 원인이나 보정 초를 임의로 만들지 않아요."],
  ["F06", "대회 없이 달리는 즐거움", "PERSONAL", ["ANSWERS"], "METHODS", "대회 외에 관심 있는 루틴과 배울 거리를 직접 고를 수 있어요.", "대회에 나가지 않는다고 감점하거나 참가를 요구하지 않아요."],
  ["F07", "일정과 비용 살펴보기", "COMPARISON", ["CONDITIONS"], "CALENDAR", "직접 입력한 대회 일정과 이동, 비용을 나란히 정리해요.", "모르는 금액을 0원으로 합산하거나 실시간 예약 정보처럼 표시하지 않아요."],
  ["F08", "기록과 순위, 예선 통과", "PERSONAL", ["GOAL", "LAPS", "CONDITIONS"], "RECORDS", "이번 경기의 목표와 라운드, 확인된 전개를 함께 읽어요.", "모든 종목에 같은 페이스 운영 기준을 적용하지 않아요."],
  ["G01", "한 달 동안 쌓인 거리", "PERSONAL", ["TRAINING"], "JOURNAL", "기록된 월간 총거리와 운동 날짜를 함께 확인해요.", "일부 자료만 받았다면 한 달 전체라고 표시하지 않아요."],
  ["G02", "비슷한 훈련 다시 보기", "COMPARISON", ["TRAINING"], "JOURNAL", "두 훈련의 실제 운동, 회복, 체감 기록을 나란히 읽어요.", "비슷한 구성이 곧 동일한 자극이나 향상의 원인을 뜻하지 않아요."],
  ["G03", "그때의 목표와 수행", "COMPARISON", ["PLAN_SNAPSHOT", "TRAINING"], "JOURNAL", "당시 저장된 처방을 실제 수행 기록과 비교해요.", "새 최고기록으로 과거 목표를 다시 계산하지 않아요."],
  ["G04", "내 답은 어떻게 달라졌을까", "COMPARISON", ["ANSWER_HISTORY"], "PROFILE", "같은 버전의 질문에서 바뀐 답과 그대로인 답을 비교해요.", "높아진 선호 점수를 더 나아진 사람이라는 뜻으로 쓰지 않아요."],
  ["G05", "지난 기록에서 다시 시작", "PERSONAL", ["TRAINING"], "JOURNAL", "마지막으로 남긴 사실을 읽고 현재 상태는 따로 확인해요.", "기록 공백을 실제 운동 중단으로 확정하지 않아요."],
  ["G06", "이번 주기에 확인한 사실", "PERSONAL", ["TRAINING", "PLAN_SNAPSHOT"], "PLAN_REVIEW", "해당 기간에 근거가 있는 사실만 골라 함께 살펴봐요.", "세 가지를 채우려고 없는 결과를 만들지 않아요."],
  ["H01", "에너지 시스템 용어 읽기", "EDUCATION", ["REVIEWED_SOURCE"], "GLOSSARY", "에너지 공급 경로, 훈련 목적, 일정에서의 역할을 구분해요.", "MAIN, LT, ATP-PC를 같은 분류 단계로 보지 않아요."],
  ["H02", "이 설명의 근거는 무엇일까", "EDUCATION", ["REVIEWED_SOURCE"], "EVIDENCE", "기전 연구, 훈련 효과 연구, 코칭 판단과 선수 사례를 구분해요.", "논문 링크가 있다는 것만으로 모든 주장이 검증된 것은 아니에요."],
  ["H03", "워치 숫자 읽는 법", "EDUCATION", ["REVIEWED_SOURCE"], "EVIDENCE", "기기가 직접 측정한 값과 모델로 추정한 값을 나눠 읽어요.", "공개되지 않은 기기 계산식을 만들어 설명하지 않아요."],
  ["H04", "같은 반복, 다른 회복", "EDUCATION", ["REVIEWED_SOURCE"], "METHODS", "운동 숫자가 같아도 회복과 세트 구성이 다른 예를 비교해요.", "거리 기준 그림을 시간 비례 그림처럼 표시하지 않아요."],
  ["H05", "한 문제로 배우기", "EDUCATION", ["REVIEWED_SOURCE"], "QUIZ", "합성 사례의 질문을 풀고 근거가 있는 해설을 읽어요.", "퀴즈 정답률은 신체 능력 점수가 아니에요."],
  ["H06", "예시 일지를 읽는 방법", "EDUCATION", ["REVIEWED_SOURCE"], "EXAMPLE", "합성 사례 또는 공개 허가된 자료로 일지를 읽는 방법을 배워요.", "예시를 개인의 실제 기록처럼 표시하거나 개인 메모를 무단 사용하지 않아요."],
]

export const ORACLE_CONTENT_CATALOG = Object.freeze(rows.map(([id, title, kind, evidence, destination, explanation, limitation]) => Object.freeze({
  id, group: id[0]!, title, kind, requiredEvidence: Object.freeze([...evidence]), destination,
  explanation, limitation, version: "ORACLE_CONTENT_CATALOG_V2_1" as const,
  sourceDocument: "reports/plans/ORACLE_FULL_SCOPE_BUILD_MATRIX_2026-10-04.md",
  sourceTopicId: id,
  personalizedRendererReady: false as const,
})))
export function oracleContentTopic(id: string) { return ORACLE_CONTENT_CATALOG.find(topic => topic.id === id) ?? null }
