import React from "react"
import { cleanup, fireEvent, render, screen, waitFor, within } from "@testing-library/react"
import { afterEach, beforeEach, expect, it, vi } from "vitest"
import { OracleProfileExperience, type OracleProfileExperienceProps } from "./OracleProfileExperience"
import { ORACLE_CONTENT_CATALOG } from "../domain/oracle-content-catalog"
import { ORACLE_QUESTIONS } from "../domain/oracle-profile-v2"

vi.mock("../hooks/useReaderDialog", () => ({ useReaderDialog: (ref: React.RefObject<HTMLDialogElement>, close: () => void) => {
  React.useEffect(() => { ref.current?.showModal() }, [ref])
  return close
} }))
function props(extra: Partial<OracleProfileExperienceProps> = {}): OracleProfileExperienceProps {
  return { answers: {}, selectedCharacter: null, revision: 0, readings: [], account: false, status: "READY",
    readTopic: () => ({ state: "MISSING", facts: [], paragraphs: ["입력한 자료가 없어요."], limitations: ["없는 자료는 추측하지 않아요."] }),
    onDraft: vi.fn(), onCommit: vi.fn(async () => true), onRemember: vi.fn(async () => true),
    onDelete: vi.fn(async () => true), onRetry: vi.fn(), onBack: vi.fn(), onNavigate: vi.fn(), ...extra }
}
beforeEach(() => { HTMLDialogElement.prototype.showModal = function () { this.setAttribute("open", "") } })
afterEach(cleanup)
const dialog = () => screen.getByRole("dialog", { hidden: true })
const openSettings = () => fireEvent.click(screen.getByRole("button", { name: "마리·친구·프로필 설정" }))
const openTopics = () => fireEvent.click(screen.getByText("전체 주제·다른 글"))

it("shows a complete six-axis chart without treating optional strength preferences as radar axes", () => {
  const answers = Object.fromEntries(ORACLE_QUESTIONS.map(q => [q.id, q.axisId === "INTENSITY" ? 1 : 4]))
  render(<OracleProfileExperience {...props({ answers, selectedCharacter: "STRUCTURE" })} />)
  const chart = screen.getByRole("img", { name: /러닝 취향/ })
  expect(chart.querySelectorAll(".preference-radar__point")).toHaveLength(6)
  expect(chart.querySelector(".preference-radar__shape")).not.toBeNull()
  expect(chart.getAttribute("aria-label")).toContain("강한 달리기: 0점")
  expect(chart.getAttribute("aria-label")).not.toMatch(/웨이트|보조 운동/)
  expect(screen.getByText("보조 운동·웨이트 취향")).toBeVisible()
})

it("opens an unanswered radar axis directly without committing a fabricated result", () => {
  const p = props({ answers: { STRUCTURE_1: 5, STRUCTURE_2: 5, STRUCTURE_3: 5 } })
  render(<OracleProfileExperience {...p} />)
  fireEvent.click(screen.getByRole("button", { name: /^함께 달리기, 답 더하기/ }))
  expect(within(dialog()).getByRole("heading", { name: ORACLE_QUESTIONS.find(q => q.id === "SOCIAL_1")!.text })).toBeVisible()
  expect(p.onCommit).not.toHaveBeenCalled()
})

it("reviews existing radar answers and edits just one without asking the whole axis again", async () => {
  const answers = { STRUCTURE_1: 5, STRUCTURE_2: 5, STRUCTURE_3: 5, SOCIAL_1: 2, SOCIAL_2: 2, SOCIAL_3: 2 } as const
  const p = props({ answers, selectedCharacter: "STRUCTURE" })
  render(<OracleProfileExperience {...p} />)
  fireEvent.click(screen.getByRole("button", { name: /^계획, 100점/ }))
  fireEvent.click(within(dialog()).getByRole("button", { name: "내 답 수정" }))
  expect(within(dialog()).getByRole("heading", { name: "내 답을 정리했어요" })).toBeVisible()
  fireEvent.click(within(dialog()).getByText("내 답 확인·수정"))
  fireEvent.click(within(dialog()).getByRole("button", { name: `${ORACLE_QUESTIONS.find(q => q.id === "STRUCTURE_2")!.text} 매우 그래요` }))
  fireEvent.click(within(dialog()).getByRole("button", { name: "그런 편이에요" }))
  await waitFor(() => expect(p.onCommit).toHaveBeenCalledOnce())
  expect(p.onCommit).toHaveBeenCalledWith({ ...answers, STRUCTURE_2: 4 }, "STRUCTURE")
})

it("does not draw an empty radar or assign a character when every answer is uncertain", () => {
  render(<OracleProfileExperience {...props({ answers: { STRUCTURE_1: "UNKNOWN", STRUCTURE_2: "UNKNOWN", STRUCTURE_3: "SKIPPED" } })} />)
  expect(screen.queryByRole("img")).toBeNull()
  expect(screen.queryByRole("button", { name: /캐릭터 이야기$/ })).toBeNull()
  fireEvent.click(screen.getByRole("button", { name: "훈련 계획 응답 보기" }))
  expect(within(dialog()).getByText(/숫자 0과 달라요/)).toBeVisible()
})

it("makes the user's preference result the subject before optional guidance and settings", () => {
  render(<OracleProfileExperience {...props({ answers: { STRUCTURE_1: 5, STRUCTURE_2: 5, STRUCTURE_3: 5 }, selectedCharacter: "STRUCTURE" })} />)
  const self = screen.getByRole("region", { name: "나의 러닝 프로필" })
  expect(within(self).getByRole("heading", { name: "계획을 즐기는 러너" })).toBeVisible()
  expect(within(self).getByRole("heading", { level: 1, name: "계획을 즐기는 러너" })).toHaveClass("app-heading--screen", "app-heading--accent")
  const chart = within(self).getByRole("img", { name: /러닝 취향.*계획: 100점/ })
  expect(chart).toBeVisible()
  expect(chart.querySelectorAll(".preference-radar__point")).toHaveLength(1)
  expect(chart.querySelector(".preference-radar__shape")).toBeNull()
  expect(within(self).queryByText("마리 매니저")).toBeNull()
  const character = within(self).getByRole("button", { name: "계획을 챙기는 여우 캐릭터 이야기" })
  expect(character).toBeVisible()
  expect(character.compareDocumentPosition(chart) & Node.DOCUMENT_POSITION_FOLLOWING).not.toBe(0)
  expect(within(self).getByText("점수가 높을수록 그 항목에 동의했어요. 실력 점수는 아니에요.")).toBeVisible()
  expect(screen.queryByRole("complementary", { name: "마리의 내 응답 해설" })).toBeNull()
})
it("introduces a tappable guide without making Mari the user's preference type", () => {
  const { rerender } = render(<OracleProfileExperience {...props()} />)
  expect(screen.queryByRole("complementary")).toBeNull()
  expect(screen.getByRole("heading", { name: "나는 어떤 달리기를 좋아할까요?" })).toBeVisible()
  expect(screen.getByRole("button", { name: "마리의 답변 팁" })).toBeVisible()
  openSettings()
  expect(screen.getByRole("complementary").querySelector("img")).toHaveAttribute("src", expect.stringContaining("mari-explain.webp"))
  fireEvent.click(within(dialog()).getByRole("button", { name: "닫기" }))
  for (const axis of ["STRUCTURE", "SOCIAL", "REFRESH"] as const) {
    rerender(<OracleProfileExperience {...props({ answers: { [`${axis}_1`]: 5, [`${axis}_2`]: 5, [`${axis}_3`]: 5 }, selectedCharacter: axis })} />)
    expect(screen.getByRole("button", { name: /캐릭터 이야기$/ })).toBeVisible()
    expect(screen.queryByRole("complementary")).toBeNull()
  }
})
it("hides decorative manager guidance during pending, failed and conflicting account reads", () => {
  const answers = { STRUCTURE_1: 5, STRUCTURE_2: 5, STRUCTURE_3: 5 } as const
  const view = render(<OracleProfileExperience {...props({ account: true, answers })} />)
  expect(screen.getByRole("button", { name: "마리의 결과 안내" })).toBeVisible()
  for (const status of ["LOADING", "PENDING", "FAILED", "CONFLICT"] as const) {
    view.rerender(<OracleProfileExperience {...props({ account: true, answers, status })} />)
    expect(view.container.querySelector("img")).toBeNull()
    expect(screen.getByRole("status")).toBeVisible()
  }
})
it("keeps preference explanations and settings usable when the companion image fails", () => {
  const view = render(<OracleProfileExperience {...props({ answers: { STRUCTURE_1: 5, STRUCTURE_2: 5, STRUCTURE_3: 5 } })} />)
  fireEvent.error(view.container.querySelector("img")!)
  expect(view.container.querySelector("img")).toBeNull()
  expect(screen.getByRole("heading", { name: "내가 고른 달리기 취향" })).toBeVisible()
  expect(screen.getByRole("button", { name: "마리의 결과 안내" })).toBeVisible()
  openSettings()
  expect(dialog()).toBeVisible()
})
it("opens the requested library view with a contextual return label", () => {
  render(<OracleProfileExperience {...props({ initialView: "library", backLabel: "읽을거리로 돌아가기" })} />)
  expect(screen.getByRole("article", { name: "먼저 읽을 글" })).toBeVisible()
  expect(screen.getByRole("group", { name: "읽을거리 주제" })).not.toBeVisible()
  expect(within(screen.getByRole("article", { name: "먼저 읽을 글" })).getByRole("heading", { level: 1 })).toHaveClass("app-heading--screen", "app-heading--accent")
  expect(screen.getByRole("button", { name: "읽을거리로 돌아가기" })).toBeVisible()
  expect(screen.getByText("오라클 읽을거리")).toBeVisible()
})
it("reads an existing article first and resumes the last opened article without hiding its evidence", () => {
  render(<OracleProfileExperience {...props({ initialView: "library", readTopic: id => ({ state: "EDUCATION", facts: [], paragraphs: [`기존 글 본문 ${id}`], limitations: ["이 글의 한계"] }) })} />)
  const featured = screen.getByRole("article", { name: "먼저 읽을 글" })
  expect(within(featured).getByText("기존 글 본문 D02")).toBeVisible()
  expect(screen.getByRole("group", { name: "읽을거리 주제" })).not.toBeVisible()
  openTopics()
  fireEvent.click(screen.getByRole("button", { name: "내가 달리는 이유" }))
  expect(within(dialog()).getByText("기존 글 본문 A01")).toBeVisible()
  fireEvent.click(within(dialog()).getByRole("button", { name: "닫기" }))
  expect(within(featured).getByText("기존 글 본문 A01")).toBeVisible()
  fireEvent.click(within(featured).getByText("이 풀이의 기준과 한계"))
  expect(within(featured).getByText("이 글의 한계")).toBeVisible()
})
it("prioritizes the first survey and preserves manager and friend actions in a named profile menu", () => {
  const p = props()
  render(<OracleProfileExperience {...p} />)
  expect(screen.getByRole("button", { name: "내 훈련 방식 알아보기 · 질문 3개" })).toBeVisible()
  expect(screen.queryByRole("navigation", { name: "러닝 프로필 보기" })).toBeNull()
  expect(screen.queryByRole("button", { name: "친구와 취향 비교" })).toBeNull()
  openSettings()
  for (const name of ["내 훈련 해설", "친구와 취향 비교"]) {
    const button = screen.getByRole("button", { name })
    expect(button).toBeVisible()
    expect(button.closest("details")).toBeNull()
  }
  expect(screen.getByRole("button", { name: "내 기록 해설" })).not.toBeVisible()
  fireEvent.click(screen.getByText("기록·계획 해설"))
  expect(screen.getByRole("button", { name: "내 기록 해설" })).toBeVisible()
  expect(screen.getByRole("button", { name: "계획·수행 비교" })).toBeVisible()
  fireEvent.click(screen.getByRole("button", { name: "친구와 취향 비교" }))
  expect(p.onNavigate).toHaveBeenCalledWith("FRIENDS")
})
it("opens real record and plan readings from the manager and returns to the same profile", () => {
  const readTopic = vi.fn((id: string) => ({ state: "READY" as const, facts: [{ label: "확인한 자료", value: id === "B02" ? "800m · 2:08" : id === "C02" ? "기록된 훈련 · 3회" : "당시 목표 · 200m 32초", source: "합성 시험 자료" }], paragraphs: [], limitations: [] }))
  render(<OracleProfileExperience {...props({ readTopic, answers: { STRUCTURE_1: 5, STRUCTURE_2: 5, STRUCTURE_3: 5 }, selectedCharacter: "STRUCTURE" })} />)
  openSettings()
  let manager = within(screen.getByRole("complementary", { name: "마리 매니저" }))
  fireEvent.click(manager.getByText("마리의 안내"))
  fireEvent.click(manager.getByText("기록·계획 해설"))
  fireEvent.click(manager.getByRole("button", { name: "내 기록 해설" }))
  expect(readTopic).toHaveBeenLastCalledWith("B02", { STRUCTURE_1: 5, STRUCTURE_2: 5, STRUCTURE_3: 5 })
  expect(within(dialog()).getByText("800m · 2:08")).toBeInTheDocument()
  fireEvent.click(within(dialog()).getByRole("button", { name: "닫기", hidden: true }))
  expect(screen.getByRole("heading", { name: "계획을 즐기는 러너" })).toBeVisible()
  openSettings()
  manager = within(screen.getByRole("complementary", { name: "마리 매니저" }))
  fireEvent.click(manager.getByText("기록·계획 해설"))
  fireEvent.click(manager.getByRole("button", { name: "계획·수행 비교" }))
  expect(readTopic).toHaveBeenLastCalledWith("C07", { STRUCTURE_1: 5, STRUCTURE_2: 5, STRUCTURE_3: 5 })
  expect(within(dialog()).getByText("당시 목표 · 200m 32초")).toBeInTheDocument()
  fireEvent.click(within(dialog()).getByRole("button", { name: "닫기", hidden: true }))
  openSettings()
  manager = within(screen.getByRole("complementary", { name: "마리 매니저" }))
  fireEvent.click(manager.getByRole("button", { name: "내 훈련 해설" }))
  expect(readTopic).toHaveBeenLastCalledWith("C02", { STRUCTURE_1: 5, STRUCTURE_2: 5, STRUCTURE_3: 5 })
  expect(within(dialog()).getByText("기록된 훈련 · 3회")).toBeInTheDocument()
})
it("does not invent a personal training analysis for an empty or loading profile", () => {
  const { rerender } = render(<OracleProfileExperience {...props()} />)
  expect(screen.getByRole("button", { name: "내 훈련 방식 알아보기 · 질문 3개" })).toBeVisible()
  expect(screen.queryByRole("meter")).toBeNull()
  openSettings()
  const manager = within(screen.getByRole("complementary"))
  fireEvent.click(manager.getByText("마리의 안내"))
  fireEvent.click(manager.getByText("기록·계획 해설"))
  fireEvent.click(manager.getByRole("button", { name: "계획·수행 비교" }))
  expect(within(dialog()).getByText("입력한 자료가 없어요.")).toBeInTheDocument()
  expect(within(dialog()).queryByText(/체력|능력.*점|회복력/)).toBeNull()
  fireEvent.click(within(dialog()).getByRole("button", { name: "닫기", hidden: true }))
  rerender(<OracleProfileExperience {...props({ account: true, status: "LOADING" })} />)
  openSettings()
  fireEvent.click(screen.getByText("마리의 안내"))
  expect(within(screen.getByRole("complementary")).getByText("계정의 응답을 확인하는 중이에요.")).toBeVisible()
  expect(screen.queryByRole("button", { name: "내 취향 풀이" })).toBeNull()
})

it("moves optional context into profile settings and keeps its unfinished action direct", () => {
  const onContext = vi.fn()
  const { rerender } = render(<OracleProfileExperience {...props({ onContext })} />)
  const self = screen.getByRole("region", { name: "나의 러닝 프로필" })
  expect(screen.queryByRole("button", { name: /^훈련·대회 정보 추가/ })).toBeNull()
  openSettings()
  const contextAction = screen.getByRole("button", { name: /^훈련·대회 정보 추가/ })
  expect(screen.getByRole("button", { name: "내 훈련 방식 알아보기 · 질문 3개" })).toBeVisible()
  expect(self.compareDocumentPosition(contextAction) & Node.DOCUMENT_POSITION_FOLLOWING).not.toBe(0)
  expect(contextAction).toBeVisible()
  expect(contextAction.closest("details")).toBeNull()
  fireEvent.click(contextAction)
  expect(onContext).toHaveBeenCalledOnce()

  rerender(<OracleProfileExperience {...props({ onContext, responsesDisabled: true })} />)
  expect(screen.getByRole("button", { name: "작성하던 추가 맥락 이어가기" })).toBeVisible()
  expect(screen.queryByText("훈련·대회 정보 추가")).toBeNull()
})

it("uses a concise, honest transient message for guest responses", () => {
  render(<OracleProfileExperience {...props()} />)
  expect(screen.getByText("게스트 · 임시 응답은 새로고침하면 사라져요.")).toBeVisible()
})

it("keeps account pending status visible with its retry action", () => {
  const onRetry = vi.fn()
  render(<OracleProfileExperience {...props({ account: true, status: "PENDING", message: "계정 저장을 기다리고 있어요.", onRetry })} />)
  const pending = screen.getByText("계정 저장을 기다리고 있어요.")
  expect(pending).toBeVisible()
  expect(pending.closest("details")).toBeNull()
  fireEvent.click(screen.getByRole("button", { name: "다시 확인" }))
  expect(onRetry).toHaveBeenCalledOnce()
})
it("describes a loading account without hiding its status", () => {
  render(<OracleProfileExperience {...props({ account: true, status: "LOADING" })} />)
  expect(screen.getByText("계정에서 불러오는 중").closest("details")).toBeNull()
  openSettings()
  const manager = within(screen.getByRole("complementary", { name: "마리 매니저" }))
  fireEvent.click(manager.getByText("마리의 안내"))
  expect(manager.getByText("계정의 응답을 확인하는 중이에요.")).toBeVisible()
})
it("keeps the manager's preference explanation tied to the selected result", () => {
  render(<OracleProfileExperience {...props({ answers: { STRUCTURE_1: 5, STRUCTURE_2: 5, STRUCTURE_3: 5 }, selectedCharacter: "STRUCTURE" })} />)
  fireEvent.click(within(screen.getByRole("region", { name: "나의 러닝 프로필" })).getByRole("button", { name: /^계획, 100점/ }))
  expect(dialog()).toHaveAttribute("aria-label", "마리의 응답 해설")
  expect(within(dialog()).getByText("마리 매니저 · 내 응답 기준")).toBeInTheDocument()
  expect(within(dialog()).getByText(/세 문항의 응답을 정리한 100점/)).toBeInTheDocument()
})

it("asks one question at a time and only commits after the third response", async () => {
  const p = props(); render(<OracleProfileExperience {...p} />)
  fireEvent.click(screen.getByRole("button", { name: "내 훈련 방식 알아보기 · 질문 3개" }))
  expect(screen.getByText(/선택 사항이에요/u)).toBeVisible()
  for (let n = 0; n < 3; n++) {
    expect(within(dialog()).getAllByRole("heading", { hidden: true })).toHaveLength(1)
    expect(within(dialog()).getByRole("heading", { level: 1, hidden: true })).toHaveClass("app-heading--screen", "app-heading--accent")
    fireEvent.click(within(dialog()).getByRole("button", { name: "매우 그래요", hidden: true }))
    if (n < 2) expect(p.onCommit).not.toHaveBeenCalled()
  }
  await waitFor(() => expect(p.onCommit).toHaveBeenCalledTimes(1))
  expect(p.onDraft).toHaveBeenCalledTimes(3)
  expect(p.onCommit).toHaveBeenCalledWith({ STRUCTURE_1: 5, STRUCTURE_2: 5, STRUCTURE_3: 5 }, "STRUCTURE")
})
it("announces nonnumeric and skipped answers as selected when revisiting a question", () => {
  render(<OracleProfileExperience {...props()} />)
  fireEvent.click(screen.getByRole("button", { name: "내 훈련 방식 알아보기 · 질문 3개" }))

  const answerWithoutCertainty = () => {
    fireEvent.click(within(dialog()).getByText("답하기 어려워요"))
    return within(dialog()).getByRole("button", { name: "상황마다 달라요", hidden: true })
  }
  fireEvent.click(answerWithoutCertainty())
  fireEvent.click(within(dialog()).getByRole("button", { name: "이전 질문", hidden: true }))
  expect(answerWithoutCertainty()).toHaveAttribute("aria-pressed", "true")

  fireEvent.click(within(dialog()).getByRole("button", { name: "건너뛰기", hidden: true }))
  fireEvent.click(within(dialog()).getByRole("button", { name: "이전 질문", hidden: true }))
  expect(within(dialog()).getByRole("button", { name: "건너뛰기", hidden: true })).toHaveAttribute("aria-pressed", "true")
  expect(answerWithoutCertainty()).toHaveAttribute("aria-pressed", "false")
})
it("preserves answers on save rejection and exposes the failure instead of success", async () => {
  const p = props({ account: true, onCommit: vi.fn(async () => false) }); render(<OracleProfileExperience {...p} />)
  fireEvent.click(screen.getByRole("button", { name: "내 훈련 방식 알아보기 · 질문 3개" }))
  for (let n = 0; n < 3; n++) fireEvent.click(within(dialog()).getByRole("button", { name: "매우 그래요", hidden: true }))
  await waitFor(() => expect(screen.getByRole("alert")).toHaveTextContent("입력한 답은"))
  expect(within(dialog()).getByText("100")).toBeInTheDocument()
  fireEvent.click(within(dialog()).getByRole("button", { name: "다시 저장", hidden: true }))
  await waitFor(() => expect(p.onCommit).toHaveBeenCalledTimes(2))
})
it("reopens an edited complete-axis draft from its first question without confirming it", () => {
  const answers = { STRUCTURE_1: 5, STRUCTURE_2: 5, STRUCTURE_3: 5 } as const
  const p = props({ answers, draftAnswers: { ...answers, STRUCTURE_1: 1 } })
  render(<OracleProfileExperience {...p} />)
  fireEvent.click(screen.getByRole("button", { name: "작성하던 답 이어가기" }))
  expect(within(dialog()).getByText("1 / 3")).toBeInTheDocument()
  expect(p.onCommit).not.toHaveBeenCalled()
})
it("lets a user keep a neutral character despite an eligible candidate", async () => {
  const p = props({ answers: { STRUCTURE_1: 5, STRUCTURE_2: 5, STRUCTURE_3: 5 }, selectedCharacter: "STRUCTURE" })
  render(<OracleProfileExperience {...p} />)
  fireEvent.click(screen.getByText("대표 별명 선택"))
  fireEvent.click(screen.getByRole("button", { name: "별명 없이 보기" }))
  await waitFor(() => expect(p.onCommit).toHaveBeenCalledWith(p.answers, null))
})
it("does not offer a fake zero score for skipped responses", async () => {
  render(<OracleProfileExperience {...props()} />)
  fireEvent.click(screen.getByRole("button", { name: "내 훈련 방식 알아보기 · 질문 3개" }))
  for (let n = 0; n < 3; n++) fireEvent.click(within(dialog()).getByRole("button", { name: "건너뛰기", hidden: true }))
  await waitFor(() => expect(within(dialog()).getByText("점수 없이 답만 정리했어요.")).toBeInTheDocument())
  expect(dialog().querySelector(".oracle-v2__result-number")).toBeNull()
  expect(within(dialog()).queryByText("0")).toBeNull()
})
it("exposes every topic in its group without inventing personal facts", () => {
  render(<OracleProfileExperience {...props()} />)
  fireEvent.click(screen.getByRole("button", { name: "읽을거리" }))
  openTopics()
  const names = ["취향", "경기 기록", "훈련", "훈련법", "함께", "대회", "돌아보기", "배우기"]
  names.forEach((name, i) => {
    fireEvent.click(within(screen.getByRole("group", { name: "읽을거리 주제" })).getByRole("button", { name }))
    const topics = ORACLE_CONTENT_CATALOG.filter(topic => topic.group === String.fromCharCode(65 + i))
    topics.forEach(topic => expect(screen.getByRole("button", { name: topic.title })).toBeVisible())
  })
})
it("keeps the originating topic when opening and closing a learning reader", () => {
  render(<OracleProfileExperience {...props()} />)
  fireEvent.click(screen.getByRole("button", { name: "읽을거리" }))
  openTopics()
  fireEvent.click(screen.getByRole("button", { name: "배우기" }))
  fireEvent.click(screen.getByRole("button", { name: "한 문제로 배우기" }))
  fireEvent.click(within(dialog()).getByRole("button", { name: "문제 풀기", hidden: true }))
  const learning = document.querySelector<HTMLDialogElement>('dialog[aria-label="오라클 배움"]')!
  expect(document.querySelector('dialog[aria-label="한 문제로 배우기"]')).toBeInTheDocument()
  fireEvent.click(within(learning).getByRole("button", { name: "닫기", hidden: true }))
  expect(document.querySelector('dialog[aria-label="오라클 배움"]')).toBeNull()
  expect(document.querySelector('dialog[aria-label="한 문제로 배우기"]')).toBeInTheDocument()
})
it("does not discard a topic when its linked records view is opened", () => {
  const p = props(); render(<OracleProfileExperience {...p} />)
  fireEvent.click(screen.getByRole("button", { name: "읽을거리" }))
  openTopics()
  fireEvent.click(screen.getByRole("button", { name: "경기 기록" }))
  const topic = ORACLE_CONTENT_CATALOG.find(item => item.group === "B" && item.destination === "RECORDS")!
  fireEvent.click(screen.getByRole("button", { name: topic.title }))
  fireEvent.click(within(dialog()).getByRole("button", { name: "경기 기록 보기", hidden: true }))
  expect(p.onNavigate).toHaveBeenCalledWith("RECORDS")
  expect(dialog()).toHaveAttribute("aria-label", topic.title)
})
it("labels A03's calendar destination accurately and keeps its originating topic open", () => {
  const p = props(); render(<OracleProfileExperience {...p} />)
  fireEvent.click(screen.getByRole("button", { name: "읽을거리" }))
  openTopics()
  const topic = ORACLE_CONTENT_CATALOG.find(item => item.id === "A03")!
  fireEvent.click(screen.getByRole("button", { name: topic.title }))
  const origin = dialog()
  expect(within(origin).queryByRole("button", { name: "계획 보기", hidden: true })).toBeNull()
  fireEvent.click(within(origin).getByRole("button", { name: "달력 보기", hidden: true }))
  expect(p.onNavigate).toHaveBeenCalledExactlyOnceWith("CALENDAR")
  expect(dialog()).toBe(origin)
  expect(origin).toHaveAttribute("aria-label", topic.title)
})
it("clears a failed bookmark message when retry succeeds", async () => {
  const onRemember = vi.fn().mockResolvedValueOnce(false).mockResolvedValueOnce(true)
  render(<OracleProfileExperience {...props({ account: true, answers: { STRUCTURE_1: 5, STRUCTURE_2: 5, STRUCTURE_3: 5 }, onRemember })} />)
  fireEvent.click(screen.getByRole("button", { name: "이 결과 보관" }))
  await waitFor(() => expect(screen.getByRole("alert")).toBeInTheDocument())
  fireEvent.click(screen.getByRole("button", { name: "이 결과 보관" }))
  await waitFor(() => expect(onRemember).toHaveBeenCalledTimes(2))
  expect(screen.queryByRole("alert")).toBeNull()
})

it("confirms the previous choice and lets it be changed without losing later answers", async () => {
  const p = props()
  render(<OracleProfileExperience {...p} />)
  fireEvent.click(screen.getByRole("button", { name: "내 훈련 방식 알아보기 · 질문 3개" }))
  expect(within(dialog()).getByRole("heading")).toHaveFocus()
  expect(within(dialog()).getByRole("progressbar", { name: "현재 질문 순서" })).toHaveAttribute("value", "1")
  fireEvent.click(within(dialog()).getByRole("button", { name: "그런 편이에요" }))
  expect(within(dialog()).getByRole("button", { name: "이전 답 그런 편이에요" })).toBeVisible()
  expect(within(dialog()).getByRole("progressbar")).toHaveAttribute("value", "2")
  fireEvent.click(within(dialog()).getByRole("button", { name: "이전 답 그런 편이에요" }))
  expect(within(dialog()).getByRole("heading")).toHaveFocus()
  expect(within(dialog()).getByRole("button", { name: "그런 편이에요" })).toHaveAttribute("aria-pressed", "true")
  fireEvent.click(within(dialog()).getByRole("button", { name: "보통이에요" }))
  fireEvent.click(within(dialog()).getByRole("button", { name: "매우 그래요" }))
  fireEvent.click(within(dialog()).getByRole("button", { name: "매우 그래요" }))
  await waitFor(() => expect(p.onCommit).toHaveBeenCalledOnce())
  expect(p.onCommit).toHaveBeenCalledWith({ STRUCTURE_1: 3, STRUCTURE_2: 5, STRUCTURE_3: 5 }, "STRUCTURE")
})

it("finishes one preference before offering an optional next topic and never calls it a full diagnosis", async () => {
  const p = props()
  render(<OracleProfileExperience {...p} />)
  fireEvent.click(screen.getByRole("button", { name: "내 훈련 방식 알아보기 · 질문 3개" }))
  expect(screen.queryByRole("button", { name: "마리의 답변 팁" })).toBeNull()
  for (let n = 0; n < 3; n++) fireEvent.click(within(dialog()).getByRole("button", { name: "매우 그래요" }))
  await waitFor(() => expect(within(dialog()).getByRole("button", { name: "기록 도전도 알아보기" })).toBeEnabled())
  expect(screen.getAllByRole("button", { name: "계획을 챙기는 여우 캐릭터 이야기" })).toHaveLength(1)
  expect(within(dialog()).getByText("계획 선호 · 내 응답 기준")).toBeVisible()
  expect(within(dialog()).getByText("취향을 정리한 값이에요. 체력이나 실력 점수가 아니에요.")).toBeVisible()
  expect(within(dialog()).getByRole("button", { name: "내 결과 보기" })).toBeVisible()
  expect(within(dialog()).queryByText(/진단 완료|분석 완료|보상|포인트/)).toBeNull()
  fireEvent.click(within(dialog()).getByRole("button", { name: "기록 도전도 알아보기" }))
  expect(dialog()).toHaveAttribute("aria-label", "기록 도전 선호")
  expect(within(dialog()).getByRole("heading", { name: ORACLE_QUESTIONS.find(q => q.id === "CHALLENGE_1")!.text })).toHaveFocus()
  expect(p.onCommit).toHaveBeenCalledOnce()
  for (let n = 0; n < 3; n++) fireEvent.click(within(dialog()).getByRole("button", { name: "그런 편이에요" }))
  await waitFor(() => expect(p.onCommit).toHaveBeenCalledTimes(2))
  expect(p.onCommit).toHaveBeenLastCalledWith({ STRUCTURE_1: 5, STRUCTURE_2: 5, STRUCTURE_3: 5, CHALLENGE_1: 4, CHALLENGE_2: 4, CHALLENGE_3: 4 }, "STRUCTURE")
})

it("updates a reviewed answer once without making the user repeat the other questions", async () => {
  const p = props()
  render(<OracleProfileExperience {...p} />)
  fireEvent.click(screen.getByRole("button", { name: "내 훈련 방식 알아보기 · 질문 3개" }))
  for (let n = 0; n < 3; n++) fireEvent.click(within(dialog()).getByRole("button", { name: "매우 그래요" }))
  await waitFor(() => expect(p.onCommit).toHaveBeenCalledOnce())
  fireEvent.click(within(dialog()).getByText("내 답 확인·수정"))
  const second = ORACLE_QUESTIONS.find(q => q.id === "STRUCTURE_2")!
  fireEvent.click(within(dialog()).getByRole("button", { name: `${second.text} 매우 그래요` }))
  expect(within(dialog()).getByRole("heading", { name: second.text })).toHaveFocus()
  expect(within(dialog()).getByRole("button", { name: "매우 그래요" })).toHaveAttribute("aria-pressed", "true")
  expect(within(dialog()).getByText("내 답 수정")).toBeVisible()
  expect(within(dialog()).queryByRole("progressbar")).toBeNull()
  fireEvent.click(within(dialog()).getByRole("button", { name: "전혀 그렇지 않아요" }))
  await waitFor(() => expect(p.onCommit).toHaveBeenCalledTimes(2))
  expect(within(dialog()).getByRole("heading", { name: "내 답을 정리했어요" })).toHaveFocus()
  expect(p.onCommit).toHaveBeenLastCalledWith({ STRUCTURE_1: 5, STRUCTURE_2: 1, STRUCTURE_3: 5 }, null)
})

it("keeps uncertain answers unscored while making the next preference optional", async () => {
  const p = props()
  render(<OracleProfileExperience {...p} />)
  fireEvent.click(screen.getByRole("button", { name: "내 훈련 방식 알아보기 · 질문 3개" }))
  for (let n = 0; n < 3; n++) {
    fireEvent.click(within(dialog()).getByText("답하기 어려워요"))
    fireEvent.click(within(dialog()).getByRole("button", { name: "아직 모르겠어요" }))
  }
  await waitFor(() => expect(within(dialog()).getByRole("button", { name: "기록 도전도 알아보기" })).toBeEnabled())
  expect(within(dialog()).getByText("점수 없이 답만 정리했어요.")).toBeVisible()
  expect(dialog().querySelector(".oracle-v2__result-number")).toBeNull()
  expect(within(dialog()).queryByText("0")).toBeNull()
  expect(screen.queryByRole("meter")).toBeNull()
  expect(p.onCommit).toHaveBeenCalledWith({ STRUCTURE_1: "UNKNOWN", STRUCTURE_2: "UNKNOWN", STRUCTURE_3: "UNKNOWN" }, null)
})

it("cancels a single-answer review without changing answers or committing again", async () => {
  const p = props()
  render(<OracleProfileExperience {...p} />)
  fireEvent.click(screen.getByRole("button", { name: "내 훈련 방식 알아보기 · 질문 3개" }))
  for (let n = 0; n < 3; n++) fireEvent.click(within(dialog()).getByRole("button", { name: "매우 그래요" }))
  await waitFor(() => expect(p.onCommit).toHaveBeenCalledOnce())
  fireEvent.click(within(dialog()).getByText("내 답 확인·수정"))
  const first = ORACLE_QUESTIONS.find(q => q.id === "STRUCTURE_1")!
  fireEvent.click(within(dialog()).getByRole("button", { name: `${first.text} 매우 그래요` }))
  fireEvent.click(within(dialog()).getByRole("button", { name: "수정 취소" }))
  expect(within(dialog()).getByRole("heading", { name: "내 답을 정리했어요" })).toHaveFocus()
  expect(within(dialog()).getByText("100")).toBeVisible()
  expect(p.onDraft).toHaveBeenCalledTimes(3)
  expect(p.onCommit).toHaveBeenCalledOnce()
})

it("keeps failed saves inside the result dialog and prevents starting another preference", async () => {
  const p = props({ account: true, onCommit: vi.fn(async () => false) })
  render(<OracleProfileExperience {...p} />)
  fireEvent.click(screen.getByRole("button", { name: "내 훈련 방식 알아보기 · 질문 3개" }))
  for (let n = 0; n < 3; n++) fireEvent.click(within(dialog()).getByRole("button", { name: "매우 그래요" }))
  await waitFor(() => expect(within(dialog()).getByRole("alert")).toHaveTextContent("입력한 답은 이 화면에 남아 있어요."))
  expect(within(dialog()).queryByText("계정에 저장됨")).toBeNull()
  expect(within(dialog()).getByRole("button", { name: "기록 도전도 알아보기" })).toBeDisabled()
  expect(within(dialog()).queryByRole("button", { name: "마리의 결과 안내" })).toBeNull()
  expect(within(dialog()).getByRole("button", { name: "다시 저장" })).toBeEnabled()
})

it("passes the live app reduced-motion setting into the profile and the dialog", () => {
  render(<OracleProfileExperience {...props()} />)
  const motionKey = "trainoracle.calendar-reduced-motion.v1"
  window.localStorage.setItem(motionKey, "true")
  fireEvent(window, new StorageEvent("storage", { key: motionKey }))
  fireEvent.click(screen.getByRole("button", { name: "내 훈련 방식 알아보기 · 질문 3개" }))
  expect(document.querySelector("section.oracle-v2")).toHaveAttribute("data-reduced-motion", "true")
  expect(dialog()).toHaveAttribute("data-reduced-motion", "true")
  window.localStorage.removeItem(motionKey)
  fireEvent(window, new StorageEvent("storage", { key: motionKey }))
  expect(dialog()).not.toHaveAttribute("data-reduced-motion")
})
