import { chromium } from "@playwright/test"
const BASE = "http://localhost:4173"
const records = [{ schemaVersion: 1, id: "review-800", purpose: "RECENT_RESULT", eventDistanceM: 800, performanceSeconds: 120, achievedOn: "2026-08-10", seasonId: null, enteredBy: "ATHLETE", verificationState: "SELF_REPORTED", sourceRef: "athlete-record:review-800", savedAt: "2026-08-10T12:00:00.000Z" }]
const browser = await chromium.launch()
const page = await (await browser.newContext({ viewport: { width: 375, height: 667 }, serviceWorkers: "block" })).newPage()
await page.addInitScript((seed) => { window.localStorage.setItem("trainoracle.athlete-records.v1", JSON.stringify(seed)) }, records)
await page.goto(`${BASE}/?app=1`)
await page.getByRole("navigation", { name: "주 탭" }).getByRole("button", { name: "계획" }).click()
await page.getByRole("button", { name: /800m.*1500m.*3000m/u }).click()
await page.getByRole("button", { name: /일반부/u }).click()
await page.getByRole("button", { name: /구조화된 훈련과 경기 경험이 많아요/u }).click()
await page.getByRole("button", { name: /통증은 없고 몸 상태는 평소와 같아요/u }).click()
await page.getByRole("button", { name: "내 계획 완성하기" }).click()
await page.getByRole("button", { name: /반복 인터벌.*VO2/u }).click()
await page.getByRole("button", { name: /^3일/u }).click()
await page.getByRole("button", { name: /9일 계획 받기/u }).click()
await page.getByRole("button", { name: /아침에 운동해요/u }).click()
await page.getByRole("button", { name: /하루 한 번 운동/u }).click()
const picker = page.getByRole("region", { name: "개인 페이스 기준 기록" })
await picker.getByRole("button", { name: /800m/u }).click()
await picker.getByRole("button", { name: "이 기록으로 개인 페이스 적용" }).click()
await page.getByRole("button", { name: /반복 인터벌 포함 선택하기/u }).click()
await page.waitForTimeout(300)
await page.getByRole("navigation", { name: "주 탭" }).getByRole("button", { name: "홈" }).click()
await page.waitForTimeout(500)
await page.evaluate(() => window.scrollTo(0, document.body.scrollHeight))
await page.waitForTimeout(300)
await page.screenshot({ path: "e2e-review/shots/23-home-bottom.png" })
const body = await page.textContent("body")
const i = body.indexOf("다음 훈련")
console.log(JSON.stringify(body.slice(i, i + 300)))
await browser.close()
